---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkding
  namespace: tools
spec:
  interval: 10m
  chart:
    spec:
      chart: linkding
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: true

  values:
    image:
      repository: sissbruecker/linkding
      tag: 1.11.0

    env:
      TZ: ${TIMEZONE}

    persistentVolumeClaim:
      existingPersistentVolumeClaim: linkding-config-pvc

    securityContext:
      enabled: true
      runAsUser: 1031
      fsGroup: 65537
