---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app unifi
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: unifi
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    env:
      TZ: ${TIMEZONE}
      # PUID: 1031
      # PGID: 65537
      MEM_LIMIT: 1024 #optional
      MEM_STARTUP: 1024 #optional
    service:
      main:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: *app
          metallb.universe.tf/loadBalancerIPs: ${METALLB_UNIFI_INKY_ADDR}
        ports:
          http:
            port: 8443
            protocol: HTTPS
          controller:
            enabled: true
            port: 8080
            protocol: TCP
          speedtest:
            enabled: true
            port: 6789
            protocol: TCP
          stun:
            enabled: false
          syslog:
            enabled: false
          discovery:
            enabled: false
      udp:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: *app
          metallb.universe.tf/loadBalancerIPs: ${METALLB_UNIFI_INKY_ADDR}
        ports:
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
          discovery:
            enabled: true
            port: 10001
            protocol: UDP

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "router-network"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
          - host: &host "unifi-inky.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "unifi-inky-tls"

    podSecurityContext:
      runAsUser: 1031
      runAsGroup: 65537
      fsGroup: 65537
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 100
        - 109
        - 568
        - 65537

    nodeSelector:
      kubernetes.io/hostname: "inky"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - inky
    persistence:
      data:
        enabled: true
        existingClaim: unifi-data-pvc
