---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-data-pv
  namespace: networking
spec:
  storageClassName: unifi-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/volume2/DockerVol/unifi_inky_data"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-data-pvc
  namespace: networking
spec:
  storageClassName: unifi-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
