---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-data-pv-v2
  namespace: networking
spec:
  storageClassName: unifi-nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/volume2/DockerVol/unifi_inky_data"
  mountOptions:
    - nfsvers=4.1
    - hard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-data-pvc-v2
  namespace: networking
spec:
  storageClassName: unifi-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
