---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app grafana
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      version: 6.32.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system

  dependsOn:
    - name: traefik
      namespace: networking
    - name: kube-prometheus-stack
      namespace: monitoring

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    deploymentStrategy:
      type: Recreate

    env:
      GF_EXPLORE_ENABLED: true
      GF_PANELS_DISABLE_SANITIZE_HTML: true
      GF_LOG_FILTERS: rendering:debug
      # VAR_BLOCKY_URL: "http://blocky.network.svc.cluster.local:4000"

    grafana.ini:
      server:
        root_url: "https://grafana.${SECRET_DOMAIN}"
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      analytics:
        check_for_updates: false
      log:
        mode: console
      grafana_net:
        url: https://grafana.net
      security:
        allow_embedding: true

    adminUser: admin
    # adminPassword: "${SECRET_GRAFANA_ADMIN_PASSWORD}"

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
        hajimari.io/enable: "true"
        hajimari.io/icon: "chart-areaspline"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"

      hosts:
        - &host "grafana.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host
          secretName: grafana-tls

    plugins:
      - natel-discrete-panel
      - pr0ps-trackmap-panel
      - grafana-piechart-panel
      - grafana-clock-panel
      - vonage-status-panel
      - grafana-worldmap-panel

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://thanos-query:9090
            isDefault: true
          - name: Loki
            type: loki
            access: proxy
            url: http://loki:3100

    dashboards:
      default:
        # Ref: https://grafana.com/grafana/dashboards/12175
        calico-felix:
          gnetId: 12175
          revision: 5
          datasource: Prometheus
        unifi-client-insights:
          gnetId: 11315
          revision: 8
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/11311
        unifi-network-sites:
          gnetId: 11311
          revision: 4
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/11314
        unifi-uap-insights:
          gnetId: 11314
          revision: 9
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/11312
        unifi-usw-insights:
          gnetId: 11312
          revision: 8
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/13502
        minio:
          gnetId: 13502
          revision: 12
          datasource: Prometheus
        flux-cluster:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/cluster.json
          datasource: Prometheus
        flux-control-plane:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/control-plane.json
          datasource: Prometheus
          # ceph-cluster:
          #   gnetId: 2842
          #   revision: 14
          #   datasource: Prometheus
          # # Ref: https://grafana.com/grafana/dashboards/5336
          # ceph-osd:
          #   gnetId: 5336
          #   revision: 5
          #   datasource: Prometheus
          # # Ref: https://grafana.com/grafana/dashboards/5342
          # ceph-pools:
          #   gnetId: 5342
          #   revision: 5
          #   datasource: Prometheus
          # # Ref: https://grafana.com/grafana/dashboards/11315
          # nut-status:
          #   gnetId: 14104
          #   revision: 3
          #   datasource: Prometheus
          # # Ref: https://grafana.com/grafana/dashboards/11315

    podAnnotations:
      configmap.reloader.stakater.com/reload: "grafana"

    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
        folderAnnotation: grafana_folder
        provider:
          foldersFromFilesStructure: true
      datasources:
        enabled: true
        searchNamespace: ALL

    resources:
      requests:
        cpu: 75m
        memory: 128Mi
      limits:
        memory: 512Mi

  valuesFrom:
    - kind: Secret
      name: grafana
      valuesKey: admin-pass
      targetPath: adminPassword
      optional: false
