---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: 6.32.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    deploymentStrategy:
      type: Recreate
    replicas: 1
    env:
      GF_EXPLORE_ENABLED: true
      GF_PANELS_DISABLE_SANITIZE_HTML: true
      GF_LOG_FILTERS: rendering:debug
      GF_DATE_FORMATS_USE_BROWSER_LOCALE: true
      GF_DATE_FORMATS_FULL_DATE: "MMM Do, YYYY hh:mm:ss a"
      GF_DATE_FORMATS_INTERVAL_SECOND: "hh:mm:ss a"
      GF_DATE_FORMATS_INTERVAL_MINUTE: "hh:mm a"
      GF_DATE_FORMATS_INTERVAL_HOUR: "DD/MM hh:mm a"
      GF_DATE_FORMATS_INTERVAL_DAY: "DD/MM"
      GF_DATE_FORMATS_INTERVAL_MONTH: "MM-YYYY"
      GF_DATE_FORMATS_INTERVAL_YEAR: "YYYY"
      GF_SECURITY_COOKIE_SAMESITE: grafana
    admin:
      existingSecret: "grafana"
      userKey: admin-user
      passwordKey: admin-pass
    grafana.ini:
      server:
        root_url: "https://grafana.${SECRET_DOMAIN}"
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      analytics:
        check_for_updates: false
      log:
        mode: console
      grafana_net:
        url: https://grafana.net
      auth.basic:
        disable_login_form: false
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    datasources:
      datasources.yaml:
        apiVersion: 1
        # list of datasources that should be deleted from the database
        deleteDatasources:
          - name: Loki
            orgId: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-operated:9090
            access: proxy
            isDefault: true
            # - name: Prometheus
            #   type: prometheus
            #   access: proxy
            #   url: http://thanos-query:9090/
            #   # url: http://mimir-query-frontend.monitoring.svc.cluster.local:8080/prometheus
            #   isDefault: true
            # - name: Loki
            #   type: loki
            #   access: proxy
            #   url: http://loki-gateway:80
    dashboards:
      default:
        flux-cluster:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/cluster.json
          datasource: Prometheus
        flux-control-plane:
          url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/control-plane.json
          datasource: Prometheus
          # Ref: https://grafana.com/grafana/dashboards/7845
          # zfs:
          #   gnetId: 7845
          #   revision: 4
          #   datasource: Prometheus
          # Ref: https://grafana.com/grafana/dashboards/13502
          # minio:
          #   gnetId: 13502
          #   revision: 10
          #   datasource: Prometheus
          # Ref: https://grafana.com/grafana/dashboards/11315
          # unifi-client-insights:
          #   gnetId: 11315
          #   revision: 8
          #   datasource: Prometheus
          # # Ref: https://grafana.com/grafana/dashboards/11311
          # unifi-network-sites:
          #   gnetId: 11311
          #   revision: 4
          #   datasource: Prometheus
          # # Ref: https://grafana.com/grafana/dashboards/11314
          # unifi-uap-insights:
          #   gnetId: 11314
          #   revision: 9
          #   datasource: Prometheus
          # # Ref: https://grafana.com/grafana/dashboards/11312
          # unifi-usw-insights:
          #   gnetId: 11312
          #   revision: 8
          #   datasource: Prometheus
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
        # folderAnnotation: grafana_folder
        # provider:
        #   foldersFromFilesStructure: true
      datasources:
        enabled: true
        searchNamespace: ALL
    plugins:
      - natel-discrete-panel
      - pr0ps-trackmap-panel
      - grafana-piechart-panel
      - vonage-status-panel
      - grafana-worldmap-panel
      - grafana-clock-panel
    # serviceMonitor:
    #   enabled: true
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          hajimari.io/enable: "true"
          hajimari.io/icon: "server-network"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
          traefik.ingress.kubernetes.io/affinity: "cookie"
          traefik.ingress.kubernetes.io/session-cookie-name: "grafana"
          traefik.ingress.kubernetes.io/session-cookie-expires: "172800"
          traefik.ingress.kubernetes.io/session-cookie-max-age: "172800"
        hosts:
          - host: &host "grafana.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "grafana-tls"
    podSecurityContext:
      fsGroup: 100
      supplementalGroups:
        - 100
    persistence:
      enabled: true
      existingClaim: grafana-data-pvc
    # podAnnotations:
    #   configmap.reloader.stakater.com/reload: "grafana"
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - grafana
              topologyKey: kubernetes.io/hostname
