---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-nfs-pv
  namespace: monitoring
spec:
  storageClassName: grafana-nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/volume2/DockerVol/grafana_data"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-pvc
  namespace: monitoring
spec:
  storageClassName: grafana-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
