---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app loki
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: loki
      version: 2.13.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: ghcr.io/k8s-at-home/loki

    config:
      storage_config:
        aws:
          s3: s3://${SECRET_MINIO_LOKI_ACCESS_KEY}:${SECRET_MINIO_LOKI_SECRET_KEY}@${SECRET_MINIO_REGION}/loki
          endpoint: ${SECRET_MINIO_SERVER}
          s3forcepathstyle: true
        boltdb_shipper:
          active_index_directory: /data/index
          cache_location: /data/boltdb-cache
          shared_store: s3

    serviceMonitor:
      enabled: true
