---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: promtail
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 5m

  install:
    timeout: 10m
    remediation:
      retries: 3

  upgrade:
    timeout: 10m
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true

  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true

  values:
    image:
      registry: ghcr.io
      repository: k8s-at-home/promtail

    config:
      lokiAddress: http://loki:3100/loki/api/v1/push
      snippets:
        extraScrapeConfigs: |
          - job_name: syslog
            syslog:
              listen_address: 0.0.0.0:1514
              label_structured_data: true
              labels:
                job: syslog
            relabel_configs:
            - source_labels: ['__syslog_message_hostname']
              target_label: host
    extraPorts:
      syslog:
        name: syslog
        containerPort: 1514
        service:
          type: LoadBalancer
          externalIPs:
            - ${METALLB_SYSLOG_ADDR}

    serviceMonitor:
      enabled: true
