---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: code-server
  namespace: development

spec:
  interval: 5m

  chart:
    spec:
      # renovate: registryUrl=https://wrmilling.github.io/wrmilling-charts/
      chart: code-server
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: wrmilling-charts
        namespace: flux-system
      interval: 5m

  values:
    ingress:
      enabled: true

      ingressClassName: "traefik"

      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "vs-code"
        hajimari.io/group: development

        cert-manager.io/cluster-issuer: "letsencrypt-staging"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-chain-internal-no-auth@kubernetescrd"

      hosts:
        - host: &host code.${SECRET_DOMAIN}
          paths:
            - /

      tls:
        - hosts:
            - *host

    persistence:
      enabled: true
      existingClaim: code-server-pvc
      # extraVars:
      #   - name: DISABLE_TELEMETRY
      #     value: true
