---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haste-server-redis
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: redis
      version: 16.13.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    architecture: standalone
    securityContext:
      sysctls:
        - name: net.core.somaxconn
          value: "10000"
    global:
      storageClass: "nfs-client"
    master:
      podSecurityContext:
        fsGroup: 65537
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      persistence:
        enabled: true
        existingClaim: haste-redis-data
    replica:
      replicaCount: 0
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    auth:
      enabled: false
