---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring

spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: thanos
      version: 11.1.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m

  install:
    createNamespace: true
    remediation:
      retries: 5

  upgrade:
    remediation:
      retries: 5

  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring

  values:
    objstoreConfig:
      type: s3
      # config:
      #   insecure: true
      # existingObjstoreSecret: thanos-objstore
      config:
        bucket: thanos
        endpoint: "minio.dbms.svc.cluster.local:9000"
        access_key: ${SECRET_MINIO_THANOS_ACCESS_KEY}
        secret_key: ${SECRET_MINIO_THANOS_SECRET_KEY}
        region: ${SECRET_MINIO_REGION}
        insecure: true

    query:
      enabled: true
      replicaCount: 1
      podAntiAffinityPreset: hard
      replicaLabels:
        - replica

      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring

      ingress:
        enabled: true

        ingressClassName: "traefik"
        hostname: "thanos.${SECRET_DOMAIN}"

        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"

        tls: true

      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 60
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - i386
                      - i686
                      - x86

    queryFrontend:
      enabled: false

    bucketweb:
      enabled: true
      replicaCount: 1
      podAntiAffinityPreset: hard

      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 60
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - i386
                      - i686
                      - x86

    compactor:
      enabled: false
      retentionResolutionRaw: 7d
      retentionResolution5m: 30d
      retentionResolution1h: 180d
      persistence:
        enabled: true
        existingClaim: thanos-compactor-data-pvc

      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 60
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - i386
                      - i686
                      - x86

    storegateway:
      enabled: false
      replicaCount: 1
      podAntiAffinityPreset: hard
      persistence:
        enabled: true
        existingClaim: thanos-storegateway-data-pvc

      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 60
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - i386
                      - i686
                      - x86

    ruler:
      enabled: false
      replicaCount: 1
      podAntiAffinityPreset: hard
      dnsDiscovery:
        enabled: true

      alertmanagers:
        - http://kube-prometheus-stack-alertmanager.monitoring:9093

      clusterName: wutanglan

      extraFlags:
        - "--web.prefix-header=X-Forwarded-Prefix"

      config: |-
        groups:
          - name: "PrometheusWatcher"
            rules:
              - alert: "PrometheusDown"
                expr: absent(up{job="kube-prometheus-stack-prometheus"})

      persistence:
        enabled: true
        existingClaim: thanos-ruler-data-pvc

      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 60
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - i386
                      - i686
                      - x86

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
