---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app thanos
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: thanos
      version: 10.5.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
  values:
    image:
      registry: public.ecr.aws
      repository: bitnami/thanos
    objstoreConfig:
      type: s3
      config:
        bucket: *app
        endpoint: minio.dbms:9000
        access_key: *app
        insecure: true
    query:
      enabled: true
      replicaCount: 1
      replicaLabels:
        - __replica__
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring
      ingress:
        enabled: true
        hostname: "thanos.${SECRET_DOMAIN}"
        ingressClassName: "traefik"
        path: /
        pathType: Prefix
        tls: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
    queryFrontend:
      enabled: false
    bucketweb:
      enabled: true
    compactor:
      enabled: true
      extraFlags:
        - "--compact.concurrency"
        - "4"
      retentionResolutionRaw: 30d
      retentionResolution5m: 30d
      retentionResolution1h: 30d
      persistence:
        enabled: false
    storegateway:
      enabled: true
      containerSecurityContext:
        enabled: true
        runAsUser: 1001
      podSecurityContext:
        enabled: true
        fsGroup: 65537
      persistence:
        enabled: true
        existingClaim: thanos-storegateway-data
    ruler:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  valuesFrom:
    - kind: Secret
      name: *app
      valuesKey: secret-key
      targetPath: objstoreConfig.config.secret_key
