---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: thanos-storegateway-data-pv
  namespace: monitoring
spec:
  storageClassName: thanos-storegateway-data-nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/volume2/DockerVol/thanos_storegateway_data"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thanos-storegateway-data
  namespace: monitoring
spec:
  storageClassName: thanos-storegateway-data-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
