---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: thanos-storegateway-data-pv
  namespace: monitoring
spec:
  storageClassName: thanos-storegateway-data-nfs
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/volume2/DockerVol/thanos_storegateway_data"
  mountOptions:
    - nfsvers=4.1
    - hard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thanos-storegateway-data-pvc
  namespace: monitoring
spec:
  storageClassName: thanos-storegateway-data-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
