---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: thanos-compactor-data-pv
  namespace: monitoring
spec:
  storageClassName: thanos-compactor-data-nfs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/volume2/DockerVol/thanos_compactor_data"
  mountOptions:
    - nfsvers=4.1
    - hard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thanos-compactor-data-pvc
  namespace: monitoring
spec:
  storageClassName: thanos-compactor-data-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
