---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: 5.8.2
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 15m

  install:
    createNamespace: true
    remediation:
      retries: 5

  upgrade:
    remediation:
      retries: 5

  values:
    fullnameOverride: blackbox-exporter
    image:
      repository: quay.io/prometheus/blackbox-exporter

    allowIcmp: true

    config:
      modules:
        icmp:
          prober: icmp
          timeout: 30s
          icmp:
            preferred_ip_protocol: "ip4"
        http_2xx:
          prober: http
          timeout: 30s
          http:
            valid_http_versions: ["HTTP/1.0", "HTTP/1.1", "HTTP/2.0"]
            no_follow_redirects: false
            preferred_ip_protocol: "ip4"
        tcp_connect:
          prober: tcp
          timeout: 30s

    serviceMonitor:
      enabled: true
      defaults:
        labels:
          release: prometheus
        interval: 2m
        scrapeTimeout: 30s
      targets:
        - name: udm
          url: 192.168.1.1
          module: icmp
        - name: homelab-switch-flex-mini-one
          url: 192.168.1.143
          module: icmp
        - name: homelab-switch-flex-mini-two
          url: 192.168.1.106
          module: icmp
        - name: office-switch-flex-mini
          url: 192.168.1.238
          module: icmp
        - name: long-range-ap
          url: 192.168.1.176
          module: icmp
        - name: synology-nas
          url: "${NAS_ADDR}"
          module: icmp
        - name: hue-bridge
          url: 192.168.20.122
          module: icmp

    prometheusRule:
      enabled: true
      additionalLabels:
        app: prometheus-operator
        release: prometheus
        namespace: monitoring
      rules:
        - alert: HostDown
          expr: probe_success == 0
          for: 10m
          labels:
            severity: critical
          annotations:
            message: The host {{"{{ $labels.target }}"}} is currently unreachable
        - alert: SlowResponseTime
          annotations:
            message: The response time for {{"{{ $labels.target }}"}} has been greater than 30 seconds for 5 minutes.
          expr: probe_duration_seconds > 30
          for: 15m
          labels:
            severity: warning
        - alert: BlackboxSslCertificateWillExpireSoon
          expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 3
          for: 15m
          labels:
            severity: critical
          annotations:
            description: |-
              The SSL certificate for {{"{{ $labels.target }}"}} will expire in less than 3 days
        - alert: BlackboxSslCertificateExpired
          expr: probe_ssl_earliest_cert_expiry - time() <= 0
          for: 15m
          labels:
            severity: critical
          annotations:
            description: |-
              The SSL certificate for {{"{{ $labels.target }}"}} has expired
        - alert: BlackboxProbeFailed
          expr: probe_success == 0
          for: 15m
          labels:
            severity: critical
          annotations:
            description: |-
              The host {{"{{ $labels.target }}"}} is currently unreachable

    ingress:
      enabled: true
      pathType: Prefix
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - "blackbox.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - "blackbox.${SECRET_DOMAIN}"
          secretName: blackbox-exporter-tls
