---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpa
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: vpa
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
      interval: 15m
  timeout: 20m
  values:
    recommender:
      enabled: true

      requests:
        cpu: 15m
        memory: 110M
      limits:
        memory: 316M

      extraArgs:
        pod-recommendation-min-cpu-millicores: 15
        pod-recommendation-min-memory-mb: 61
        storage: prometheus
        prometheus-address: http://prometheus-prometheus.monitoring:9090
        # prometheus-address: http://thanos-query:9090/

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - inky

    updater:
      enabled: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - inky
