---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: anonaddy-mariadb
  namespace: tools
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 11.6.15
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: bitnami/postgresql
      tag: 11.15.0-debian-10-r28
    auth:
      username: anonaddy
      password: "${SECRET_ANONADDY_DB_PASSWORD}"
      database: anonaddy
    primary:
      persistence:
        enabled: true
        existingClaim: anonaddy-mariadb-data
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
