---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: mosquitto
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    force: true
    remediation:
      retries: -1
  values:
    image:
      repository: ghcr.io/k8s-at-home/eclipse-mosquitto
      tag: v2.0.14
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${METALLB_MQTT_ADDR}"
        externalTrafficPolicy: Local
    auth:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: mosquitto
    persistence:
      data:
        enabled: true
        existingClaim: mosquitto-config-v1
      configinc:
        enabled: true
        type: configMap
        mountPath: /mosquitto/configinc
        name: mqtt-conf
      mosquitto-pwd:
        enabled: true
        type: secret
        mountPath: /mosquitto/configinc/auth
        name: mosquitto-pwd
