---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app jellyfin
  namespace: media

spec:
  interval: 15m

  chart:
    spec:
      chart: jellyfin
      version: 9.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system

  dependsOn:
    - name: intel-gpu-plugin
      namespace: kube-system

    - name: node-feature-discovery
      namespace: kube-system

    - name: metallb
      namespace: networking

  values:
    global:
      nameOverride: *app

    image:
      repository: jellyfin/jellyfin
      tag: 10.8.1

    env:
      TZ: "${TIMEZONE}"
      JELLYFIN_CACHE_DIR: "/config/cache"

    # podSecurityContext:
    # runAsUser: 1031
    # runAsGroup: 65537
    # fsGroup: 65537
    # fsGroupChangePolicy: "OnRootMismatch"
    # supplementalGroups:
    #   - 100
    #   - 568
    #   - 65537

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local

        annotations:
          metallb.universe.tf/loadBalancerIPs: "${METALLB_JELLYFIN_ADDR}"

        ports:
          http:
            port: 8096

    ingress:
      main:
        enabled: true

        ingressClassName: "traefik"

        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "movie-open-play"

          # cert-manager.io/cluster-issuer: "letsencrypt-production"
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"

        hosts:
          - host: &host "jellyfin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix

        tls:
          - hosts:
              - *host
            secretName: "jellyfion-tls"

    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config-pvc

      media:
        enabled: true
        existingClaim: jellyfin-media-pvc
        mountPath: /media
        readOnly: true

      transcode:
        enabled: true
        type: emptyDir
        medium: Memory

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                    - inky
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"

    resources:
      requests:
        # cpu: 15m
        # memory: 545M
        cpu: 100m
        memory: 1000Mi
        gpu.intel.com/i915: 1

      limits:
        # cpu: 54m
        # memory: 6489M
        memory: 6000Mi
        gpu.intel.com/i915: 1
