# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: jellyfin-media-pv
#   namespace: media
# spec:
#   storageClassName: jellyfin-media-nfs
#   capacity:
#     storage: 50Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   nfs:
#     server: ${NAS_ADDR}
#     path: "/volume2/Media"
#   mountOptions:
#     - nfsvers=4
#     - tcp
#     - intr
#     - hard
#     - noatime
#     - nodiratime
#     - nolock

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # name: jellyfin-media-pvc
  name: jellyfin-media
  namespace: media
spec:
  # storageClassName: jellyfin-media-nfs
  storageClassName: nfs-client-media
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
