---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-config-pv
  namespace: home
spec:
  storageClassName: hassio-nfs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/volume2/DockerVol/homeassistant_data"
  mountOptions:
    - nfsvers=4.1
    - hard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-pvc
  namespace: home
spec:
  storageClassName: hassio-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
