apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      # registryUrl=https://k8s-at-home.com/charts/
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2022.7.2
    env:
      TZ: "${TIMEZONE}"
    envFrom:
      - secretRef:
          name: *app
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    service:
      main:
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          hajimari.io/enable: "true"
          hajimari.io/icon: "house"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
          - host: &host "hassio.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "hassio-tls"

    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-pvc
      # media:
      #   enabled: true
      #   mountPath: /mnt/media/nvr
      #   existingClaim: "nvr-media-pvc"

    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.5.0
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: "traefik"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-staging"
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
            traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
          hosts:
            - host: &host-code "haconfig.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
                  # backend:
                  #   service:
                  #     name: *app
                  #     port:
                  #       number: 8443
          tls:
            - hosts:
                - *host-code
              secretName: "hassio-config-tls"
        volumeMounts:
          - name: config
            mountPath: /config
