apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-ip-pool
spec:
  addresses:
    - ${METALLB_LB_RANGE}
    # - ${METALLB_LB_RANGE_V6}

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-l2-network
spec:
  ipAddressPools:
    - metallb-ip-pool
