apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: networking
spec:
  addresses:
    - ${METALLB_LB_RANGE}
    # - ${METALLB_LB_RANGE_V6}

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: networking
spec:
  ipAddressPools:
    - default
