---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: db
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: redis
      version: 16.13.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    master:
      persistence:
        enabled: true
        existingClaim: "redis-data-pvc"
    replica:
      replicaCount: 0
    metrics:
      enabled: true
    auth:
      password: ${SECRET_REDIS_PASSWORD}
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: redis
#   namespace: db
# spec:
#   interval: 5m
#   chart:
#     spec:
#       # renovate: registryUrl=https://charts.bitnami.com/bitnami
#       chart: redis
#       version: 16.13.2
#       sourceRef:
#         kind: HelmRepository
#         name: bitnami
#         namespace: flux-system
#       interval: 5m
#   values:
#     architecture: standalone
#     auth:
#       password: ${SECRET_REDIS_PASSWORD}
#     master:
#       service:
#         annotations:
#           prometheus.io/probe: "true"
#           prometheus.io/protocol: tcp
#     replica:
#       persistence:
#         enabled: false
#       service:
#         annotations:
#           prometheus.io/probe: "true"
#           prometheus.io/protocol: tcp
