# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: recyclarr
    namespace: media
type: Opaque
stringData:
    RADARR_APIKEY: ENC[AES256_GCM,data:ByM1ikFq+WUPzAhSisWVBhLJWywxC9ES5I/9XKpfM+s=,iv:9uJ7TvXptmnZ7qn1IXJXFor89TEF5QikDxUPt9asRxY=,tag:LnCUJGFAXSEejeAH7KCO2Q==,type:str]
    RADARR_UHD_APIKEY: ENC[AES256_GCM,data:BPae8L+uoNw0JHNf6bfSmlKz4W/0kOfJtWRuLfEF3M8=,iv:pcgbb50kDKi3ElpjvNVqvF/V3IFLda5zT2AcBtPllTM=,tag:3kBiZr01M66GHvhG+5+zFA==,type:str]
    SONARR_APIKEY: ENC[AES256_GCM,data:V2+ZDSEG50CwXRqwgIwJofhTlv8S3qsT7FQrXLdWKG8=,iv:mhtrlINmo8GKoR5ZJRjKqqI8QZJbI90voLARiHXXb2c=,tag:EyoU8J1MSquYozZqdThJ5g==,type:str]
    SONARR_UHD_APIKEY: ENC[AES256_GCM,data:bY9q8VV6YHRyvUEOb5svUp0zRhs5xWZY8H6q6cU5DAM=,iv:HEcoIV/1c4zZSsaKnUyajoUA2JzGYLfkCji4nFZVPj4=,tag:rSo2HQCAbvVtU9+H2apzyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzrw396e67z9wdzsxzdk7ka0g2gr3l460e0slaea563zll3hdfqwqxdta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SzdoQ0loZ3lXSVhTa2xx
            SWRGZGEwR2NQQjFLSlpXOGs4dHRpMFpYdURRCjFEY1dtTVY1RXhuRWx2N1ZFV25l
            SHhsZlozMWV4ck0vR1o0Sncwd2NXRlEKLS0tIDZLcWswWEp6dGtycFVONy9xNnl0
            aUV2RmN2U2MyZEUrbUZnVlY3d3hIcFUKp40tmI5HM3iumet9Z04aU/MdBDEWbWhi
            zlOcZFKkgrL5a1HyBkv4eXWIas10C2cci0cd3Q6Z2UCFgEHWuki5JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-21T00:01:03Z"
    mac: ENC[AES256_GCM,data:3KA87RbPyDCloWaZCfzmP56ypxR7e6sbZ/EIFfZnFJvih4nDAJ9Z9Kl9YX2NF3CWvifHji6mloM04E1cHEqd9a79VJFNioV29g+2iMN4CrjXpUDtwOzUqmZoAi5QjHsPa2tp0JUbdu+NbrerOTRHHtwbKsTYsVXLHyCnc6E6NIY=,iv:55wnCnRJXCQ/7nNq5ps5khj9xzsvCaEc5qYjOfgzjEc=,tag:vzzwkIbEYz0iA5gipU06tQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
