---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: goldilocks
      version: 6.1.4
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5

  values:
    controller:
      resources:
        requests:
          cpu: 10m
          memory: 64M
        limits:
          memory: 250M

    dashboard:
      replicaCount: 1

      ingress:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: cloud-download
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-chain-internal-no-auth@kubernetescrd"
        hosts:
          - host: &host "goldilocks.${SECRET_DOMAIN}"
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - *host
            # secretName: "${SECRET_DOMAIN//./-}-tls"

            # resources:
            #   requests:
            #     cpu: 10m
            #     memory: 64Mi
            #   limits:
            #     memory: 100M
