---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app minio
  namespace: dbms

spec:
  interval: 15m

  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m

  dependsOn:
    - name: metallb
      namespace: networking

  values:
    nameOverride: minio

    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2022-05-26T05-48-41Z

    env:
      TZ: "${TIMEZONE}"
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_UPDATE: "off"

    envFrom:
      - secretRef:
          name: *app

    args:
      - server
      - /data
      - --address
      - :9000
      - --console-address
      - :9001

    service:
      main:
        enabled: true

        type: LoadBalancer
        loadBalancerIP: ${METALLB_MINIO_ADDR}

        ports:
          http:
            enabled: true
            port: 9001

          api:
            enabled: true
            port: 9000

    ingress:
      main:
        enabled: true
        ingressClassName: traefik

        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "database"

          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"

        hosts:
          - host: &host-minio "minio.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 9001

          - host: &host-s3 "s3.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 9000

        tls:
          - hosts:
              - *host-minio

          - hosts:
              - *host-s3

    persistence:
      data:
        enabled: true
        existingClaim: dbms-minio-pvc
        mountPath: /data

    podAnnotations:
      secret.reloader.stakater.com/reload: *app

    resources:
      requests:
        cpu: 93m
        memory: 184M
      limits:
        cpu: 93m
        memory: 184M
