---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs-pv
  namespace: dbms
spec:
  storageClassName: minio-nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/volume2/Documents/S3"
  mountOptions:
    - nfsvers=4.1
    - hard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbms-minio-pvc
  namespace: dbms
spec:
  storageClassName: minio-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
