---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: speedtest-exporter
      version: 5.3.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/miguelndecarvalho/speedtest-exporter
      tag: v3.5.1
    env:
      TZ: ${TIMEZONE}
      SPEEDTEST_SERVER: speedtest.${SECRET_DOMAIN}
    service:
      main:
        ports:
          http:
            enabled: false
          metrics:
            enabled: true
            protocol: TCP
            port: 9798
    nodeSelector:
      worker: yes
    prometheus:
      podMonitor:
        enabled: true
        interval: 1h
        scrapeTimeout: 1m
