---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cert-manager
  # - descheduler
  - intel-gpu-plugin
  # - kube-cleanup-operator
  - kured
  # - metrics-server
  - node-feature-discovery
  - reflector
  - reloader
