apiVersion: v1
kind: Secret
metadata:
    name: authelia
    namespace: auth
stringData:
    JWT_TOKEN: ENC[AES256_GCM,data:OyDjcE+dq/89fZvz8hZsoTdxqI1mZfqzFpsu3LxtUvz4J+NPdGe9DFWdLs2SHO7BEWxR4RpVqxbvgN3OFlVRhg==,iv:C7IKrD7t3KBNy4F16lBnrMfiSh9HvJsTfkdKqJLoGkI=,tag:FWe1WMOWs7iT+Obbf3WXRw==,type:str]
    SESSION_ENCRYPTION_KEY: ENC[AES256_GCM,data:rHOhawyE5pkI2kJ9d7KLzgNr4lkc9zNo4zLWbTugBAsnB2I1T5MftmnFs1KqM9807s4nPsSzvn8gJhOqvxVlLKWzk4O//e/D439qdkw=,iv:yO/QZx+WL4MHvTj1fjRufdpRPgCmc8zlx+x3SbAs37c=,tag:YsOquT8jEeC0wnfbGjUXiw==,type:str]
    STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:nh9xPEYOpNqcq+2HL7t/zJmuODVAK/MqmSw7z//gd2m7X+M7L7Tn42WkyvFt88MNWJU6ivIqJ3e36umdpDYfOnlDnjeI,iv:nuYbtYVgRZ/1DchR+KFK/jR6BHpwohs0Z0r6MlZJlYA=,tag:kIRcTCxZjH6geq7h440b4w==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:x65TYsjFhv31vKbSC39AC/hkQYXqej66o0ssdcTfLqYCYSuEKHGXRREBp/8yMSJ0g3cJnhHjQSA8V96Nu6k+kQ==,iv:QWpxvAgu2Dnk0PPEapCfr/RSANDsPtwfnUTdAHsw6AI=,tag:m1UXTLNNJzv/6J2dkLnViQ==,type:str]
    STORAGE_PASSWORD: ENC[AES256_GCM,data:vOToVVSMYTdbexe6dAqpapbUjsbDxnXu1AUCrV71MaHCzYw0r9bv8h++6fhwkVewsY36CxOSsNAa+fzWBWMtPw==,iv:BwU0rSXuORbuAxLBu3e1EVXLB2zwZUN45DszSG9rW/4=,tag:Jgo0UNrS/6yqtNCAULPxHw==,type:str]
    #ENC[AES256_GCM,data:eZYvn7MJ6CFAo31p65zo,iv:gHTfv7pybHGrlrF7r6qsNERZeN5HlEP301A4BLtCuwE=,tag:68SI1E/BIdryhwLwFnk5hw==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p3uljw85dn69pj2q0j4sane83hhzlpywrmrs3pwkgfs6g299rg3su5udnm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NU5XQ2lDdnhBdGJ4ck1j
            ZFBmcWc3ZFpoMDlNQVQrYlIxTlc2Z2NTZlRBCjZ4U1FHU3Z1YWtLZnRDU2M4bk0y
            QU5HNGF2STdQWG1ibnN4MmQ2TTMzQnMKLS0tIDhJSS82UmVYQnlvRVIrVFpQSWdo
            WVNrZ1VnOWo5UGhXZ1ppalZIM0NsaGcKlTDgmTKSaz0UBVWv/k06STGTTNVRRkWY
            qvjzUkKpVr/MVp1tjlY6g0IlKY/4M+2lT9wVt2EzmDkx/somq/Z1AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-09T15:59:08Z"
    mac: ENC[AES256_GCM,data:JQuPA//da+jUXQ6vqUkbR/E7n9HwDlewW0KlX1taODYHP2Q17xaud/BDqTGSaRVPMDSIo5nt1BcSlExbsIwi3lVioAsSV7ptuWlKMyezTlHSgZ156DP34mmC2AthsyLZs2TAg76A0sL/rwspX/IFD3OAYWK41VJk3jwtuVO6cPM=,iv:8UzZ0TFXb7XfyVvWJ4D/yvjdqShNpIVPFwX+udy6yLQ=,tag:GRxdMPSx7Asmdp7+1C281A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
