apiVersion: v1
kind: Secret
metadata:
    name: authelia
    namespace: auth
stringData:
    JWT_TOKEN: ENC[AES256_GCM,data:Lp3nK0+uXLsFZ2yyrnAIE94fsoIwKx83BOVeokg9Ml24FYm37iUxKej7JT1fm5BaBLQzIyENjYosQrxnJsKFyg==,iv:oR1djfT7VaaBw+uduvr63ICQkT4PNz5Y1AIdrJTU1JE=,tag:4SDNF2sR8bNs3auY9V9m8A==,type:str]
    SESSION_ENCRYPTION_KEY: ENC[AES256_GCM,data:4BTKRSoowOM64VWeezXc4TG3d5usn2aJTRlssrBsRe6Bw/emjJwEFIMvt5EoqUGNGe7OBCiRZRAlit1syLkQvqA7l47lnM7KL3D8Txg=,iv:QAttZlegi4slW2iqVusR61x/RV8HwVVYIFiW58leFiA=,tag:T+LMrCOO9LgNiyFofhADsA==,type:str]
    STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:F2E9Cfyb6GSyiTjmH+hpfw+taqEut0wEr/Ecq5SkHKxD8LtPCrj1T8TOSfELH/YeC/0hVWr2MeULWmGO5xjd/sAJfP86,iv:Da9s4Z8cLahVT93YCjuYUBfHdXmleligjOmJDE+CWdk=,tag:WVg+yxsWa6UvjG7ZjVDj9A==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:cWI8Dfy7Vzsu0B5o3/k31c6FLAe1mk9/twm85gB9eVp/zE9MwfP3t2oaFJzztCzJVpyjRWHJBB3MqqOWSe9l/Q==,iv:jCVKNBV5ZXyv3kHLLhEOxwyxDPymDhbpaj9J0XuIN3Q=,tag:4ZfD32C7V931y9N9JD6DMA==,type:str]
    STORAGE_PASSWORD: ENC[AES256_GCM,data:8Kv5eopKMGEb9n3etJB7+zIgsA4/kIZjTmP5c0s9BskUUuFPuB0xlEnodCHPf1KdD4Sa7xuLEi/UAFqdss4eZA==,iv:25NSgPp4bRc9W/8DgD5AvXN6PUgz8zicpjqbMi2hCwA=,tag:nHih6LUg94pOkQC/j2WlGQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:yYUgSGmLaUEEGU4AOcNE3g==,iv:2Mg5PS9NnNtytR+0QeKFK2bczGCDkaLz3rfADXaeSKU=,tag:nKd5+jNTVpRf8Kt3E6M1rQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p3uljw85dn69pj2q0j4sane83hhzlpywrmrs3pwkgfs6g299rg3su5udnm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPalRYcWM3NGtPeHZTSDBF
            MEM1T0tBbVhQVGVPZnJneU5VVnN2NkRub2hRCmltVnN4c1dkb3pmRmE4VEJ5UUta
            M3p1czJwRG5RSGxFYi9YVHFjTS9YeTQKLS0tIFUzSXVLWUE5Z2pTWnRFYUtQcGpS
            c1dEcldVS2ovMEx0VjAvWVRmbWxPOGsKZueeRCLCZqvVUsh1yJFaMIPkG/jSN87d
            WLCzuPAZyvdowUwH/iU0xPiODAHc8pKfxCqQbuSCCzdLTXakT1+M6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T04:35:48Z"
    mac: ENC[AES256_GCM,data:6F0SZHK10u9bVZSxjndyUpxfj5Ujv3+1KLByEyhkWH7UOB/pynNVbvSYbJuqiQd6JUOMj1sOidT0Sj9cCZ1Uk7ja8OKsdvxFzIGr5DrwRPrkM3UB7pjuCnQefmFIkOfFflMxyRF5jdSAA3ewHP3m6dHOalkL0tO7bNSBD1FGoRc=,iv:9uWdjItpmU+gGu5PMOx6D4+IcZvkH4f/qANPXy+RWMc=,tag:o2cAp0dMCZvqfgyL565jhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
