---
theme: dark
authentication_backend:
  ldap:
    enabled: false
  file:
    enabled: true
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8
access_control:
  default_policy: deny
  # networks:
  #   - name: private
  #     networks:
  #       - ${WIREGUARD_VPN_NETWORK}
  rules:
    # Disable Authelia for local network
    # - policy: bypass
    #   domain: "*.${SECRET_DOMAIN}"
    #   networks:
    #     - private
    - policy: bypass
      domain: "auth.${SECRET_DOMAIN}"
    # No public access
    # - policy: deny
    #   domain:
    #     - mailu.${SECRET_DOMAIN}
    #   resources:
    #     - "^/admin.*$"
    # Applications with built-in auth
    - policy: one_factor
      domain:
        - traefik.${SECRET_DOMAIN}
        # - grafana.${SECRET_DOMAIN}
        # - rancher.${SECRET_DOMAIN}
        # - bw.${SECRET_DOMAIN}
        # - cloud.${SECRET_DOMAIN}
    # Applications without auth
    - policy: two_factor
      domain:
        "*.${SECRET_DOMAIN}"
        # - longhorn.${SECRET_DOMAIN}
        # - homer-config.${SECRET_DOMAIN}
ntp:
  address: "time.cloudflare.com:123"
  version: 3
  max_desync: 3s
  disable_startup_check: true
  disable_failure: true
session:
  name: authelia_session
  same_site: lax
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  redis:
    enabled: true
    enabledSecret: true
    host: authelia-redis-master
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m
storage:
  postgres:
    enabled: true
    host: authelia-postgresql
    database: authelia
    username: authelia
notifier:
  disable_startup_check: true
  filesystem:
    enabled: true
    filename: /config/notification.txt
  smtp:
    enabled: false
