---
kind: ConfigMap
apiVersion: v1
metadata:
  name: authelia-config-map
  namespace: auth
data:
  # notifications.txt: "placeholder"
  users_database.yml: |
    users:
      shotcowboystyle:
        displayname: "Curtis Blanton"
        password: "${SECRET_AUTHELIA_ADMIN_PASSWORD}"
        email: ${SECRET_AUTHELIA_ADMIN_EMAIL}
        groups:
          - admins
          - dev
