---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app authelia
  namespace: auth
spec:
  interval: 5m
  chart:
    spec:
      chart: authelia
      version: 0.8.38
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
      interval: 5m
  values:
    domain: ${SECRET_DOMAIN}
    service:
      annotations:
        prometheus.io/probe: "true"
        prometheus.io/protocol: "http"

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
        hajimari.io/enable: "true"
        hajimari.io/icon: "lock"
        hajimari.io/appName: "Authelia"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
      subdomain: auth
      tls:
        enabled: true
        secret: authelia-tls
      traefikCRD:
        enabled: true
        disableIngressRoute: true
        entryPoints:
          - websecure
        middlewares:
          auth:
            nameOverride: authelia-auth
            authresponseHeaders:
              - Remote-User
              - Remote-Groups
          chains:
            auth:
              nameOverride: authelia-chain

    pod:
      kind: Deployment
      replicas: 1
      strategy:
        type: Recreate
      extraVolumeMounts:
        - name: users-database
          mountPath: /config
      extraVolumes:
        - name: users-database
          configMap:
            name: authelia-users-database
            items:
              - key: users_database.yml
                path: users_database.yml

    configMap:
      theme: dark
      authentication_backend:
        ldap:
          enabled: false
        file:
          enabled: true
          path: /config/users_database.yml
          password:
            algorithm: argon2id
            iterations: 1
            key_length: 32
            salt_length: 16
            memory: 1024
            parallelism: 8
      access_control:
        default_policy: deny
        # networks:
        #   - name: private
        #     networks:
        #       - ${WIREGUARD_VPN_NETWORK}
        rules:
          # Disable Authelia for local network
          # - policy: bypass
          #   domain: "*.${SECRET_DOMAIN}"
          #   networks:
          #     - private
          - policy: bypass
            domain: "auth.${SECRET_DOMAIN}"
          # No public access
          # - policy: deny
          #   domain:
          #     - mailu.${SECRET_DOMAIN}
          #   resources:
          #     - "^/admin.*$"
          # Applications with built-in auth
          - policy: one_factor
            domain:
              - traefik.${SECRET_DOMAIN}
              # - grafana.${SECRET_DOMAIN}
              # - rancher.${SECRET_DOMAIN}
              # - bw.${SECRET_DOMAIN}
              # - cloud.${SECRET_DOMAIN}
          # Applications without auth
          - policy: two_factor
            domain:
              "*.${SECRET_DOMAIN}"
              # - longhorn.${SECRET_DOMAIN}
              # - homer-config.${SECRET_DOMAIN}
      ntp:
        address: "time.cloudflare.com:123"
        version: 3
        max_desync: 3s
        disable_startup_check: true
        disable_failure: true
      session:
        name: authelia_session
        same_site: lax
        expiration: 1h
        inactivity: 5m
        remember_me_duration: 1M
        redis:
          enabled: true
          enabledSecret: true
          host: authelia-redis-master
      regulation:
        max_retries: 3
        find_time: 2m
        ban_time: 5m
      storage:
        postgres:
          enabled: true
          host: authelia-postgresql
          database: authelia
          username: authelia
      notifier:
        disable_startup_check: true
        filesystem:
          enabled: false
          # filename: /config/notifications/notification.txt
        smtp:
          enabled: true
          enabledSecret: true
          username: ${SECRET_SMTP_USERNAME}
          host: ${SMPT_HOST}
          port: 587
          sender: ${SECRET_SMTP_USERNAME}
          identifier: ${SECRET_DOMAIN}
          subject: "[Authelia] {title}"
          startup_check_address: ${SECRET_SMTP_USERNAME}
    secret:
      existingSecret: authelia
    podSecurityContext:
      runAsUser: 1031
      runAsGroup: 65537
      supplementalGroups:
        - 100
