---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authelia-postgresql-pvc.yaml
  - authelia-redis-pvc.yaml
  - data-pvc.yaml
  - postgresql-helm-release.yaml
  - redis-helm-release.yaml
  - configmap.yaml
  - helm-release.yaml
  - secrets.sops.yaml
