---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authelia-notification-pv
  namespace: auth
  labels:
    app.kubernetes.io/name: "authelia-data"
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.1
    - hard
  nfs:
    path: /volume2/DockerVol/authelia_data/notifications
    server: ${NAS_ADDR}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-notification-pvc
  namespace: auth
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
