---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia-postgresql
  namespace: auth

spec:
  interval: 5m

  chart:
    spec:
      chart: postgresql
      version: 11.6.18
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: bitnami/postgresql
      tag: 14.2.0-debian-10-r28

    auth:
      username: authelia
      password: "${SECRET_AUTHELIA_DB_PASSWORD}"
      database: authelia

    primary:
      persistence:
        enabled: true
        existingClaim: authelia-postgres-data

      # resources:
      #   requests:
      #     cpu: 11m
      #     memory: 50M
      #   limits:
      #     cpu: 11m
      #     memory: 50M

    metrics:
      enabled: true

      serviceMonitor:
        enabled: true

      # resources:
      #   requests:
      #     cpu: 11m
      #     memory: 32M
      #   limits:
      #     cpu: 11m
      #     memory: 32M

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                    - inky
                # - key: kubernetes.io/hostname
                #   operator: In
                #   values:
                #     - clyde
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - i386
                    - i686
                    - x86
