---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia-postgresql
  namespace: auth
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 11.6.15
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: bitnami/postgresql
      tag: 11.15.0-debian-10-r28
    auth:
      username: authelia
      password: "${SECRET_AUTHELIA_DB_PASSWORD}"
      database: authelia
    primary:
      podSecurityContext:
        enabled: true
        fsGroup: 65537
      containerSecurityContext:
        enabled: true
        runAsUser: 1031
      persistence:
        enabled: true
        existingClaim: authelia-postgresql-data
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    affinity:
      nodeAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            nodeSelectorTerms:
              matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - inky
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
