---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia-redis
  namespace: auth
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 16.13.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    architecture: standalone
    securityContext:
      sysctls:
        - name: net.core.somaxconn
          value: "10000"
    global:
      storageClass: "nfs-client"
    master:
      podSecurityContext:
        fsGroup: 100
        supplementalGroups:
          - 100
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      persistence:
        enabled: true
        existingClaim: authelia-redis-data
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 60
            preference:
              matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - i386
                    - i686
                    - x86
    auth:
      existingSecret: authelia
      existingSecretPasswordKey: REDIS_PASSWORD
