apiVersion: v1
kind: Secret
metadata:
    name: authelia
    namespace: auth
stringData:
    JWT_TOKEN: ENC[AES256_GCM,data:IKia1Hwz3Og7xjkQGBkwRtf6+1iLbzdxlpcHZhpZr0x4i82x7m1og0xvAZyFFng4zxt3WaYCIdJDQdmrEE3/rA==,iv:AoWIqrCjZLLoZlSU5I66ZVQ+GRqCtLhLWOTYK4c3RZA=,tag:7hr9im2WefwrBwkdt/a+Mg==,type:str]
    SESSION_ENCRYPTION_KEY: ENC[AES256_GCM,data:Nc1CIALCoMt8+jt0YvF9hyHiM5lG3/5I9QUC5EN/nLS2BbG9Lalx8IirUpJU2hK4yVZaRVCWn0Q6xcPPDbLNhvSEX+1m2USBMQ/EzCU=,iv:4/L6V3joRQrzveynoiZvoCIhxtpcrDK3SFLbN0eC6wA=,tag:zaXO0RVpCwz0wFlAtlnuyA==,type:str]
    STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:3D4hnXYLfbprvsE+FM40h9lTqeIHuo7wxn7fMzaHRHxDM1bw03YWAGhHFG1un1eARbhenEA8Ohj113ddtFg3O4OK2wKi,iv:NbJIqR2BR/gdPnaRYkv/wni4L6C95Gq3fO8IwxtpkWg=,tag:g1asS4Ru1fFVoQfgAeOleg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:/SEgTlBBZT6VhLEGZ9FHBokXgRjrMzIpyDeHwUKCmtSIlN73v79mPV0KH99kXxlmNNKCezj7DCRTM0jG8eXl3g==,iv:kniw6aI6WEOVIdEGPyX8lcts7b4oXuTr2DSiaz9otms=,tag:FB1V2fIF6aPGIDB/fj3flw==,type:str]
    STORAGE_PASSWORD: ENC[AES256_GCM,data:/hfBW+zfcjv8PmzGeJGMUe16AnflctaBgkD9kFscRiFrF4B9TOPmNa4FofNHAqEmIvtUg8y4ZBz4jI1ZwCgTYQ==,iv:m419LgwU6dG3OYVBi/ALg9sy9oPNIR2nq3jYqE8Sqjs=,tag:LUVUKitZC19cgKNuJFglkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p3uljw85dn69pj2q0j4sane83hhzlpywrmrs3pwkgfs6g299rg3su5udnm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOXl3Zng4aUlpKzJxM1Nm
            eEZzcU5nNFZhSUh3Y3c5dG5RQm44cGpQS0dBCldlbEpoRFpwY3JtNk54dGE3Y29P
            ME81Mjd5ZndUaVpWK2Nxb2lZcjJpWkEKLS0tIHhwei96T24zWjRKRk93VVhtbVg1
            akh1R2d4RjlFbUFrRk4vVnpxV1ZRZlUKVr5fw4YnPIkyKFAN86ZFJTAo0/ei4OGs
            D9zECcMS3gnyj4NbHWFhQHrLG7Pl3GsOGRMWvwIA05pzAYDjx4lnYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T14:30:10Z"
    mac: ENC[AES256_GCM,data:8SU5KKJc8N8aHTRDhd0YLqdtIjnjJ4+JNFAyWfqhF5KAtcEgaRkYtRvIHM0c5W7bLO12nim2vONe5Lg9EcT29YPBWnDS6NfnaQ0riaABGY3kcvux5DceX1MtwQqDtYbxu65fMUzdWS1ODxK9pyq/AQ1YlCCH1lIBgO6ihmC+yrY=,iv:+vHRa6BJJMYmGtaIBWGKCZ3r3GZh+kpJ8eenBwLXPqo=,tag:cmpffJrUP6sVZZh8qzJq2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
