# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:LenbZa3YSF/ePkzeYcdAq8woqUX5uVzr,iv:5mgjvI6IMgxSVlaAVYqDa49sJp5P0OBHPKKJ9Iao/Yc=,tag:RrkPzZHVaCm8qCKydTC0ZA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:FWuH63ktuqJgN/uQS2TADuonAQ+8ww==,iv:yIP3RkYVusRUsg3mLGhPFrrdKN6F/f8bIDwixVeWxu0=,tag:g7HxuTW/ZL8QziPcQjoZGg==,type:str]
    SECRET_EMQX_ADMIN_PASSWORD: ENC[AES256_GCM,data:FCGItjmxgaExMLFIicfDe7ck1KSP+u1B35PaN/jL5A/iZkBFXINfxGOWLC+vaFG2kga98V4TBZD0cC0GjpPhYQ==,iv:XeU56i5H1J9CwDzEO2Hlh10MSzepw3qB2oebvHMuGUY=,tag:sn9lwX6drkVYd+uyuJhhGw==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:3E6WJ93ziVid5ksz,iv:kBNYapqCFNi7nl3/MsXL7t6TDIg/dWvpfq4paO/Vyi0=,tag:j6zz54NnNuQL8Lf5oU7l0A==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:20kw+EyPvN1h+Y6MxhL2SLZEvWuHw9yHk+r6v+Ib,iv:fg9IMSSHzFL5+nIrQp+1a5H3+bmzjFpz+IjiVyQMtqw=,tag:V5U2RjmZlu4Q4ClVtVAOSw==,type:str]
    SECRET_FRIGATE_PLUS_API_KEY: ENC[AES256_GCM,data:dOTMuB4HGFq7u9/aGqPonAoIDyj9hyqHsY7SWuEDz526M+S440zUZCEvRytTKIo/38iohukvbU5xmDTnAeATjP59Anm0ZEnemMUfx/M=,iv:wGJF1EI8dsSGLwFI1uR2TP+CA5GG2qA9sYKpqxgUXz4=,tag:8P2L6ARS8BWiXBWL3pL4dQ==,type:str]
    SECRET_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:HNeDOdcbsoA4hLWP/ci2+d690HvgqdHCt2X+dR4t7GgecJaAo9JiNA==,iv:QnJ2lVo8ySOdk+HL8mWKeZoN/c8ieCmtOK75aot6kSg=,tag:xkXei9ZZliXnlKWnkNQQDw==,type:str]
    SECRET_REDIS_PASSWORD: ENC[AES256_GCM,data:y33NeL153zA1BPUcUwunEksw+ZoYFzt9i0+jrzNtgCbGuhS8VBM39Qi7ieer3Fk5dWIFCJkv54Wp,iv:TnSvx4asfS1rRZyvOZxyvyt0kBQOV8kxzILdmeUlPCE=,tag:oyNY9uAqHon95QLIQYrwcQ==,type:str]
    SECRET_AUTHELIA_DB_PASSWORD: ENC[AES256_GCM,data:dUXpC8BXj9sJtr69ABShVfOCUMrwpjxygBNaJ27ghhcje/oZT2asmnu0N1S1ED+1foApCdjb0mVaNCfXqEkyBA==,iv:KFxc9VIrp2xK57KrmN3V1KytU52GkiX4fW23qbMpW3g=,tag:BjThZlIGKFSbtUpTpgG9qQ==,type:str]
    SECRET_AUTHELIA_ADMIN_EMAIL: ENC[AES256_GCM,data:1v2AVG6tiPR6R7hz1MUTCjOWiTDUtg==,iv:96Oy5mwSP+F5ozkvq4IeHHbxwD5oWRrYR8jtnDGtu2Q=,tag:leAXmyOrg3gT+LoTmFvcBw==,type:str]
    SECRET_AUTHELIA_ADMIN_PASSWORD: ENC[AES256_GCM,data:OTstCkJ6E+Wz5nGrP9ywhT6SVzEibtA6rdm0ABf1R2Ne76Ba26WP1rfTM1qHIrN97htarg4JKmruQAkpTvmXHS3Spy+PNAovE0PnLTb3tYcHG1JY6BI1PYD7cxttcOA5dK3q,iv:WoF2D3DTpU8OOQSA1MiXcvOQ//lLS4AVu+iBMwOQUag=,tag:JdVGw22FORXG7HFTk+Y9aA==,type:str]
    SECRET_MINIO_ACCESSKEY: ENC[AES256_GCM,data:+/AbZCxujSoIYw==,iv:xIdSBSWu/Aiu8BsIpex/iAkJFu+5bbwDZBzfp/z+Hok=,tag:jFpEv9Bbf2brX4w1H14R5Q==,type:str]
    SECRET_MINIO_SECRETKEY: ENC[AES256_GCM,data:4OR8FNad9UxL4J2aaWdGwdSf86Yko9bK1ZIX6fYMCYNZq/6/a/g2pZdkMUqbjBwbbHQurudYNiuXIu4ZIZCoXQ==,iv:DqRueSQACoYka7pZLCiIVZpF9iguYIB4ykylgEiNTHg=,tag:V+CUb2Oe860tGZTnLm/h+A==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:Us9YQPXhST6adRYYlNLy9zSe1YIMWT+4GshO+EmhFcn/CwyvsM6924cVqphLkRmvIroY+1ptwjft6DQ5H6e1rwuTxnyvaZIFsU7f5XOW2K6lody3UN6I1Gv5il6R8q1LVHoWAMcGNKZSTBsQPXn3Le3tmoLtrgYb,iv:sFYJQe3IlnDa1NB5myOuNkZ9d2isqBUoHMEaE4vdA8U=,tag:obgCpE59Xaeuc70RrIkNBQ==,type:str]
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:VarniXCXQknoiKmPLUdmTLLzS/2Jiw==,iv:8aIn1rPWALaLOXwaht8Os0tG77QljWZiwEITUfrjTMM=,tag:bY7dCZBsI8y3Bcb4dUGNyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p3uljw85dn69pj2q0j4sane83hhzlpywrmrs3pwkgfs6g299rg3su5udnm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WHlueWNXSUJxWkZlNjJl
            WmFaZkw3ODJlMU5IeGlJMW85WElMbitTdW1VCnZCYXRLNGp1VUpBdHFzM0FrSzdh
            UURQMnZCUGNtcTd4a0o2cHVsKzUxeGMKLS0tIEMyZWxlczgxWFRucFpIcU5TUjhZ
            U1drNWtqemV6U01tRUdrM094S09ic28KdpqxojnLI47kJYUFfx6zR2mpLfWHRTji
            E/LVUCZ6VhoGRBab9CnFcOcZWa4947/uJo7dXjkFVhg/ogNQ8yv9Og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T04:33:46Z"
    mac: ENC[AES256_GCM,data:7rIWtfdhhpZ5jmh48VJ7HzjfKIRwTjlNJMSuobecIRnZOHuHgwM7QnVLzlwnJSxH9L1mAHjc9IjcCJwdZu1+bsAB7naUl7G+B+ehPK3nnabB56T0seYaczOV5cV2EQNMlZvJhYreTkoP/Vemay2H6kD7n3EdDQL3q8NJakitAbM=,iv:nrd8xxohVKk7L2Yj+WIozjsSQixzzId41/jNElmH7Lk=,tag:B02RVjVxWIN2sZLap/rByw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
