# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-uhd
    namespace: media
type: Opaque
stringData:
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:rFdv3RwDOYjj6OMQUQU4gNxqYBSsioOyeImHYULV,iv:FyDs05HE9wKaeVmE6ICRhIRCtstEZP8lY8TBRhKaLvo=,tag:HIP70oSf0eEjD4Ehh7JjTA==,type:str]
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:zlXs5FLlZ430wKFdysAcLczKs6xvzVuB/1MDBXSk,iv:P1+bBQzOyOTTjRC94oS7xSDXM+ahgDfsLDuo4+iuqR0=,tag:LYlD1JlOc9DgsUeCnGqioQ==,type:str]
    SONARR__API_KEY: ENC[AES256_GCM,data:uiJiTWMGCe3Dz2I2Hu8a6IcHjGutHSIhVkXwMl01cRU=,iv:FYtF7dPMHsyCBxoGa2S6V9ddfJORbZtzpg22G/8nH3w=,tag:cf696rJRBkPeYM5KmbM/nQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzrw396e67z9wdzsxzdk7ka0g2gr3l460e0slaea563zll3hdfqwqxdta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTHF2WnpGUlJZMHZzaHpt
            eDRlaFpsV2FvM0NsWDhpbXZUT2xscGZLU1JNCldCaFRkQXpOUUlFYXFQeFZNZDJW
            WVI0TElGdWgvSVY2eVE4MFZJMTA4S00KLS0tIEJxbWc3Vi9GSnpYeWdKS1ZGdSt4
            WGxvOWp6WCtESjhRTjUxQzhXdEFoR00Kwzdyu/jzqKVkw0CFfFJZys6ZMwmTo13r
            57DoIO2tka/67G+0p+LJfzHss5BcPfoYjHLte6PDUTU7KySnAWfALQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-20T21:52:40Z"
    mac: ENC[AES256_GCM,data:k2h52Uj178hWr3jx2IPaH5LZS/auPvjmoje4y8f6maSnvH/T5PTmdr6Ow+VD2Olr2E34tEx/kojqknjRyIhfxCVIlvuRpaYrZdx3ktrfarcRLajJriRnvJtsgOzxF52ubpdtZMzTlS8GrReyznwnUhJDueFAnmMdQ1NK4amzO7Y=,iv:N4G5Ng3l6RqyShxGkrHyfCPD/9Qgn8mP/3OADBtB+Os=,tag:4V9LsOf+cW7aDryeqgBXHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
