---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-pv
  namespace: dbms
spec:
  storageClassName: redis-nfs
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/volume2/DockerVol/redis_data"
  mountOptions:
    - nfsvers=4.1
    - hard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: dbms
spec:
  storageClassName: redis-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
