---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: dbms

spec:
  interval: 5m

  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: redis
      version: 17.0.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    architecture: standalone

    securityContext:
      sysctls:
        - name: net.core.somaxconn
          value: "10000"

    global:
      storageClass: "nfs-client"

      redis:
        password: ${SECRET_REDIS_PASSWORD}

    master:
      podSecurityContext:
        fsGroup: 100
        supplementalGroups:
          - 100

      nodeSelector:
        beta.kubernetes.io/arch: amd64

      persistence:
        enabled: true
        existingClaim: redis-data-pvc

      resources:
        requests:
          cpu: 11m
          memory: 32M
        limits:
          cpu: 11m
          memory: 32M

    metrics:
      enabled: true

      serviceMonitor:
        enabled: true

      resources:
        requests:
          cpu: 11m
          memory: 32M
        limits:
          cpu: 11m
          memory: 32M

    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 60
            preference:
              matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                    - inky
                # - key: kubernetes.io/arch
                #   operator: In
                #   values:
                #     - amd64
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - clyde
