apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: joplin-postgresql-secret
    namespace: collab
data:
    postgresql-password: ""
    postgresql-postgres-password: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p3uljw85dn69pj2q0j4sane83hhzlpywrmrs3pwkgfs6g299rg3su5udnm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBER2ZrSitYZjhUNHJlVkQ5
            bWNFWmJUVzFXSjNlTnhtdk5VUXdTWk9qc2lFCkZMT24zdXY2RHlac2dhNG53bGk4
            YnRhcmNFRTUvZTAyaS81ZHIxQkNOa2sKLS0tIE52QUxVY0lOK3YwZDlEb0p6ZFJF
            SXpYQWNIVE5EV1ZDUG9SZ3JJKzJxY2cKGSugTbZcC4JuhOivmCiHwaimhPAmNyfF
            rqyqfKuN3TjHkv9uOJPbOA9SbsGO4B2pgQdi0cipokbUyOsLvE+wwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-11T17:45:42Z"
    mac: ENC[AES256_GCM,data:0saI3/Mqna+lmr2jTSDMTpCq0gUN8q6/w9RYSLVAMWFGeQOvHRvXkXBoVdRPjvbJH2MsA7k+HrNhoCn0rBe03wiViKSJIGN4U5ZpLGKwvEZVZaui2hw+dhJVakCfM9tbqrGG9CzDBQdg/wfSm8+loUiukYH9fvooy7BUEPi7yQs=,iv:v3/Wlp75awI9013z5uQG3ukgMCe9yp1ZT1fHeulD89Y=,tag:cie/vmKUhzL8JdhPTT7+cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
