---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data-pv
  namespace: db
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.1
    - hard
  nfs:
    path: /volume2/DockerVol/postgres_data
    server: ${NAS_ADDR}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-pvc
  namespace: db
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
