---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: db
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 11.6.15
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: bitnami/postgresql
      tag: 14.4.0
    auth:
      username: homelab
      password: "${SECRET_POSTGRESQL_PASSWORD}"
      database: homelab
    primary:
      podSecurityContext:
        supplementalGroups:
          - 100
      persistence:
        enabled: true
        existingClaim: postgresql-data-pvc
    # metrics:
    #   enabled: true
    #   serviceMonitor:
    #     enabled: true
