---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gatus-config-pv
  namespace: monitoring
spec:
  storageClassName: gatus-config-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/volume2/DockerVol/gatus_data"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatus-config-pvc
  namespace: monitoring
spec:
  storageClassName: gatus-config-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
