---
kind: Service
apiVersion: v1
metadata:
  name: nastrodamus
  namespace: networking
spec:
  type: ExternalName
  ports:
    - name: https
      port: 443
      targetPort: 7401
  externalName: "${NAS_ADDR}"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nastrodamus
  namespace: networking
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    kubernetes.io/ingress.class: traefik
    traefik.frontend.passHostHeader: "false"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
    hajimari.io/enable: "true"
    hajimari.io/icon: "nas"
spec:
  tls:
    - hosts:
        - "nastrodamus.${SECRET_DOMAIN}"
      secretName: "nastrodamus-tls"
  rules:
    - host: nastrodamus.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            backend:
              serviceName: nastrodamus
              servicePort: https
