# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr
    namespace: media
type: Opaque
stringData:
    PROWLARR__API_KEY: ENC[AES256_GCM,data:t8gVKuHV1h1movuvwo5gTI5+aQ+UFHSYiCm5D5n4voQ=,iv:lG35cn4di5t5X1Aw8S+DsZ2YVYzk0Mgb8XrsKOjgYXY=,tag:oTu5QvQ/QjwP7JUhrVEMBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzrw396e67z9wdzsxzdk7ka0g2gr3l460e0slaea563zll3hdfqwqxdta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTHF2WnpGUlJZMHZzaHpt
            eDRlaFpsV2FvM0NsWDhpbXZUT2xscGZLU1JNCldCaFRkQXpOUUlFYXFQeFZNZDJW
            WVI0TElGdWgvSVY2eVE4MFZJMTA4S00KLS0tIEJxbWc3Vi9GSnpYeWdKS1ZGdSt4
            WGxvOWp6WCtESjhRTjUxQzhXdEFoR00Kwzdyu/jzqKVkw0CFfFJZys6ZMwmTo13r
            57DoIO2tka/67G+0p+LJfzHss5BcPfoYjHLte6PDUTU7KySnAWfALQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-20T19:14:09Z"
    mac: ENC[AES256_GCM,data:uNUwe1nVb7kLAygrLzMJ7bgYQKKnotAiYcgzq00ezy7nw31Rz7YxL6J1KQGB1K/pkZMwqBBwkewBLwHd8Wl3+c1E6f/kWkD5tJ9NYAt+eCffFTKOnfYXW9jNn4FaKLKensCwa2IL4a88EthDEwlq9nB6XcioRsO1kVJ8avaDyI4=,iv:ajB1HlEGKOH/7vIN1gVvXPtGrn0GNWa3y+QGg0w7tb8=,tag:Y/TgK0n68Rt9n5FyBbGXww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
