---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app appdaemon
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: appdaemon
      version: 8.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    global:
      nameOverride: *app
    image:
      repository: acockburn/appdaemon
      tag: 4.0.8
    env:
      TZ: America/New_York
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cctv"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
          - host: &host "appdaemon.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            # secretName: "${SECRET_DOMAIN//./-}-tls"
    persistence:
      data:
        enabled: true
        existingClaim: appdaemon-config-pvc
