---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app qbittorrent
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 13.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  install:
    disableWait: true
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.4.3.1
    env:
      TZ: "${TIMEZONE}"
      # UMASK: "022"
      # USE_PROFILE: "true"
      # QBITTORRENT__PORT: &port 8080
      # QBITTORRENT__BT_PORT: &port-bt 50413
    service:
      main:
        ports:
          http:
            port: 8080
      bittorrent:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - "${METALLB_QBITTORRENT_ADDR}"
        ports:
          bittorrent:
            enabled: true
            port: 6881
            protocol: TCP
            targetPort: 6881
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          hajimari.io/enable: "true"
          hajimari.io/icon: cloud-download
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
          - host: &host qbittorrent.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "qbittorrent-tls"
    # podSecurityContext:
    #   supplementalGroups:
    #     - 100
    podAnnotations:
      setGateway: "true"
    settings:
      automaticPortSetup: false
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config-pvc-v2
      media:
        enabled: true
        existingClaim: qbittorrent-media-pvc-v2
        # mountPath: /media
      # cache:
      #   enabled: true
      #   type: emptyDir
      #   mountPath: /config/qBittorrent/cache
    podSecurityContext:
      # runAsUser: 568
      # runAsGroup: 568
      # fsGroup: 568
      # fsGroupChangePolicy: OnRootMismatch
      supplementalGroups:
        - 100

      # media:
      #   enabled: true
      #   type: nfs
      #   server: "expanse.${SECRET_PRIVATE_DOMAIN}"
      #   path: /tycho/Media
      #   mountPath: /media
    # resources:
    #   requests:
    #     cpu: 35m
    #     memory: 765M
    #   limits:
    #     memory: 1426M
