---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-media-pv
  namespace: media
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=16384
    - wsize=16384
  nfs:
    path: /volume2/Downloads/qbittorrent
    server: ${NAS_ADDR}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-media-pvc
  namespace: media
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
