# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sonarr
    namespace: media
type: Opaque
stringData:
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:JNK3ej9QPNDvyLuB7FQ6/DFGOOHievPfspJ8vjq6,iv:6lesgtBR/ixMR7K3f69B+SmfI4MkUPO1Q+Cp43XO9BQ=,tag:Sg7avEXgmVBV/DnDGtTL6A==,type:str]
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:bcs+hewazXiVrtuk36b0l3APw5bqXLy2L7zwJAEE,iv:HbCI/BWLSHu7p7gRovcsv48862RSTCghNLNzECDJYbI=,tag:HnZsF9ybLQx7BD2ZY6j5gQ==,type:str]
    SONARR__API_KEY: ENC[AES256_GCM,data:iTfCeISceP7XTeI7lMx73yWSZCUg9ho/tqTaYVbL7Fs=,iv:E91PSDHboNVPtpNUyvBaTV7OKCBQgGG+uAQcNGP9WLE=,tag:+/ODFYbrz+Llrbmv+kkxwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzrw396e67z9wdzsxzdk7ka0g2gr3l460e0slaea563zll3hdfqwqxdta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTHF2WnpGUlJZMHZzaHpt
            eDRlaFpsV2FvM0NsWDhpbXZUT2xscGZLU1JNCldCaFRkQXpOUUlFYXFQeFZNZDJW
            WVI0TElGdWgvSVY2eVE4MFZJMTA4S00KLS0tIEJxbWc3Vi9GSnpYeWdKS1ZGdSt4
            WGxvOWp6WCtESjhRTjUxQzhXdEFoR00Kwzdyu/jzqKVkw0CFfFJZys6ZMwmTo13r
            57DoIO2tka/67G+0p+LJfzHss5BcPfoYjHLte6PDUTU7KySnAWfALQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-20T21:52:32Z"
    mac: ENC[AES256_GCM,data:pAZ91uJNSCiO4nDwRXKfQ7TqB45xMiWfZu9HcEkN+scItBzyl7QKUifm658RL0YtmfAzg/oItpQ4R1jTgCCtOch64WE9N3XW2ZFLd1IVm7dyPfqR1lLPjcUp53CONKtdUIiu0D4NvV6Tnmn7HdFpSLkjM1l9Yv9F4BbWyaxLzZ8=,iv:qQd0iIbpFK70sgRks7BxQViTM76lIANbPvNQxyJIJaI=,tag:w31OIN/+87l3AdCA97I1Nw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
