---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-data
  namespace: media
  labels:
    kasten-io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 5Gi
