# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: unifi-poller
    namespace: monitoring
type: Opaque
stringData:
    unifi-unpoller-user: ENC[AES256_GCM,data:TcNuxA3IDwCtWKc=,iv:ZLIprP4YOjigFYSva8JLCvkJF+xHyOktGOPX40yoq00=,tag:COLy1gFwJV3rIcKJHXI3cA==,type:str]
    unifi-unpoller-password: ENC[AES256_GCM,data:nDSQ2sNaC9pfcV8KKjpbkyup9HDpAeQTrXd9edu7taxSX7f/520Sl5WF/Vot6Tz7rkIQdiVYuWYCd4Ky0pbwpg==,iv:LClCrvqdQSYY//MWWghTWUZ++TaUIwbnbwmW+P4fuwo=,tag:oA2nHUOaImJinsg09pgWww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p3uljw85dn69pj2q0j4sane83hhzlpywrmrs3pwkgfs6g299rg3su5udnm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dG5rK2IrZXVOMi8rMkxv
            dFUxR1hJUnNKb2hEMXM3WVhDZkQ4UmVhYTNJCk43bE9MMjB0VXZjNG5DVmNZRzli
            MFh3aVdKTzh0T0hYUXloOWg4TklFblkKLS0tIENsNW5HRTVSTFF0REZqa1k5NHpO
            bXpadGFwVFpiNVFBM1RkVEcrL0lPeTAKLcs8qcNEG8if5ghrFRu56cS3mrGWSaUz
            bHQtlztYIxrrWL5jT218NREm1XzslBhmwjz5rDCaebQ0EVvQRjwLYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-10T04:06:03Z"
    mac: ENC[AES256_GCM,data:Cb0xVVNnaBcnhKqgKfyKnjL684uXJvI7EdlXG1zHmrcfIju2Ozz0A4Zcuf76ELG/VTv/gjhrS55DxD6yIffi2Fa8Cv/i3zBtncQ0O7I2vt44SoVOMalq+JHvkVnzRkbmqDfjUxkFb/zb6CjeCb561MVrPe4UYchC7yvup9vXhKs=,iv:v2MbZPoRb8s9PQnOWi0ZiQB33axH4cMOC2YG1QVkz2E=,tag:NqX9hqCIJhp6eJnYOMGD6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
