---
mqtt:
  host: emqx
  topic_prefix: frigate
  user: mqtt_homelab
  password: "{FRIGATE_MQTT_PASSWORD}"

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
  cpu3:
    type: cpu
  cpu4:
    type: cpu

database:
  path: /data/frigate.db

ffmpeg:
  global_args:
    - -hide_banner
    - -loglevel
    - warning
  hwaccel_args:
    - -hwaccel
    - qsv
    - -qsv_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p

# Optional: Detect configuration
# NOTE: Can be overridden at the camera level
detect:
  enabled: True
  fps: 7
  width: 1920
  height: 1080
  max_disappeared: 25

objects:
  track:
    - person
    - cat
    - dog
  filters:
    person:
      min_area: 2500
      max_area: 100000
      threshold: 0.7
    cat:
      min_area: 2500
      max_area: 100000
      threshold: 0.7
    dog:
      min_area: 2500
      max_area: 100000
      threshold: 0.7

record:
  enabled: True
  expire_interval: 60
  retain:
    days: 1
    mode: all
  events:
    retain:
      default: 4
      mode: active_objects
    pre_capture: 25
    post_capture: 25

birdseye:
  # Optional: Enable birdseye view (default: shown below)
  enabled: True
#   # Optional: Width of the output resolution (default: shown below)
#   width: 2560
#   # Optional: Height of the output resolution (default: shown below)
#   height: 1440
#   # Optional: Encoding quality of the mpeg1 feed (default: shown below)
#   # 1 is the highest quality, and 31 is the lowest. Lower quality feeds utilize less CPU resources.
#   quality: 8
#   # Optional: Mode of the view. Available options are: objects, motion, and continuous
#   #   objects - cameras are included if they have had a tracked object within the last 30 seconds
#   #   motion - cameras are included if motion was detected in the last 30 seconds
#   #   continuous - all cameras are included always
#   mode: continuous

live:
  # Optional: Set the height of the live stream. (default: 720)
  # This must be less than or equal to the height of the detect stream. Lower resolutions
  # reduce bandwidth required for viewing the live stream. Width is computed to match known aspect ratio.
  height: 1080
  quality: 1

snapshots:
  enabled: True
  timestamp: False
  bounding_box: True
  retain:
    default: 4

rtmp:
  # Optional: Enable the RTMP stream (default: True)
  enabled: False

motion:
  #  threshold: 25
  #  contour_area: 100
  #  delta_alpha: 0.2
  #  frame_alpha: 0.2
  #  frame_height: 180
  improve_contrast: True

ui:
  use_experimental: True

cameras:
  patio:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:N8AGxdHV9DUEKjVGa5nRaHH5FodqgkJ@192.168.32.141:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://frigate:N8AGxdHV9DUEKjVGa5nRaHH5FodqgkJ@192.168.32.141:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

  garage_side:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:RrPhGaTo5g6UiKYYc8awLTwn9q3PWL5@192.168.33.142:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://frigate:RrPhGaTo5g6UiKYYc8awLTwn9q3PWL5@192.168.33.142:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

  apartment:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:oS9gwAtMoUkGysfvkjCrfy7jJseGDLb@192.168.34.143:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://frigate:oS9gwAtMoUkGysfvkjCrfy7jJseGDLb@192.168.34.143:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

  driveway:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:TvnxR99bwbBM6oufVCCuSDqZv4ttYMs@192.168.35.144:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://frigate:TvnxR99bwbBM6oufVCCuSDqZv4ttYMs@192.168.35.144:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

  driveway_entrance:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:S49t7BSb4gKNfYpHZdhidnB6py8CqxH@192.168.36.145:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://frigate:S49t7BSb4gKNfYpHZdhidnB6py8CqxH@192.168.36.145:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

  firepit:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:7Wmh6STGbXdRwKH9SxAY6bhHEHNRdGH@192.168.37.146:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://frigate:7Wmh6STGbXdRwKH9SxAY6bhHEHNRdGH@192.168.37.146:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

  house_side:
    ffmpeg:
      inputs:
        - path: rtsp://frigate:CB8y8c45T7zF3kzsSD79NGbcEZn9DNo@192.168.38.147:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://frigate:CB8y8c45T7zF3kzsSD79NGbcEZn9DNo@192.168.38.147:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac

  front_yard:
    #    zones:
    #      front_yard_ignore_zone_1:
    #        coordinates: 568,504,1280,248,1280,0,0,0,0,425
    ffmpeg:
      inputs:
        - path: rtsp://frigate:Vg5L7jWvWJbDaYWnje6httKPmJSE7q5@192.168.39.148:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://frigate:Vg5L7jWvWJbDaYWnje6httKPmJSE7q5@192.168.39.148:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy -an
