---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config-v1
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 900Gi
  volumeName: "frigate-config-pv"
