---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-data-pv
  namespace: home
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: "/mnt/ssd1/frigate/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - inky
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-data-pvc
  namespace: home
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
