---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app frigate
  namespace: home

spec:
  interval: 5m

  chart:
    spec:
      chart: frigate
      version: 8.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m

  install:
    createNamespace: true
    remediation:
      retries: 5

  upgrade:
    remediation:
      retries: 5

  dependsOn:
    - name: emqx
      namespace: home
    - name: intel-gpu-plugin
      namespace: kube-system
    - name: node-feature-discovery
      namespace: kube-system

  values:
    global:
      nameOverride: *app

    image:
      repository: docker.io/blakeblackshear/frigate
      tag: 0.11.0-beta7

    env:
      TZ: America/New_York
      LIBVA_DRIVER_NAME: "i965"
      LIBVA_DRIVER_NAME_JELLYFIN: "i965"

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${METALLB_FRIGATE_ADDR}"

        ports:
          http:
            port: &port 5000

          rtmp:
            enabled: true

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cctv"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-chain-internal-wutanglan-auth@kubernetescrd"
        hosts:
          - host: &host "frigate.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            # secretName: "${SECRET_DOMAIN//./-}-tls"

    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /api/version
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3

      readiness:
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /api/version
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3

      startup:
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /api/version
            port: *port
          failureThreshold: 30
          periodSeconds: 10

    securityContext:
      privileged: true

    configmap:
      config:
        enabled: false

    podAnnotations:
      configmap.reloader.stakater.com/reload: frigate

    persistence:
      config:
        enabled: true
        type: configMap
        name: frigate
        subPath: config.yaml
        mountPath: /config/config.yml
        readOnly: true

      data:
        enabled: true
        existingClaim: frigate-data-pvc

      media:
        enabled: true
        existingClaim: frigate-media-pvc

      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 4Gi
        mountPath: /dev/shm

      # usb:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/bus/usb
      # usb:
      #   enabled: true

    nodeSelector:
      kubernetes.io/hostname: "inky"

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - inky
                # - key: tpu
                #   operator: In
                #   values:
                #     - google-coral
                # - key: kubernetes.io/arch
                #   operator: In
                #   values:
                #     - amd64

    resources:
      requests:
        # cpu: 3110m
        # memory: 2264M
        # cpu: 800m
        # memory: 800Mi
        gpu.intel.com/i915: "1"
      limits:
        # cpu: 16551m
        # memory: 12G
        # memory: 4096Mi
        # cpu: 4000m
        gpu.intel.com/i915: "1"

  valuesFrom:
    - kind: Secret
      name: frigate
      valuesKey: plus_api_key
      targetPath: env.PLUS_API_KEY
      optional: false
    - kind: Secret
      name: frigate
      valuesKey: mqtt_password
      targetPath: env.FRIGATE_MQTT_PASSWORD
      optional: false
    - kind: Secret
      name: frigate
      valuesKey: rtsp_user
      targetPath: env.FRIGATE_RTSP_USERNAME
      optional: false
    - kind: Secret
      name: frigate
      valuesKey: rtsp_password_patio
      targetPath: env.FRIGATE_RTSP_PASSWORD_PATIO
      optional: false
    - kind: Secret
      name: frigate
      valuesKey: rtsp_password_garage_side
      targetPath: env.FRIGATE_RTSP_PASSWORD_GARAGE_SIDE
      optional: false
    - kind: Secret
      name: frigate
      valuesKey: rtsp_password_apartment
      targetPath: env.FRIGATE_RTSP_PASSWORD_APARTMENT
      optional: false
    - kind: Secret
      name: frigate
      valuesKey: rtsp_password_driveway
      targetPath: env.FRIGATE_RTSP_PASSWORD_DRIVEWAY
      optional: false
    - kind: Secret
      name: frigate
      valuesKey: rtsp_password_driveway_entrance
      targetPath: env.FRIGATE_RTSP_PASSWORD_DRIVEWAY_ENTRANCE
      optional: false
    - kind: Secret
      name: frigate
      valuesKey: rtsp_password_firepit
      targetPath: env.FRIGATE_RTSP_PASSWORD_FIREPIT
      optional: false
    - kind: Secret
      name: frigate
      valuesKey: rtsp_password_house_side
      targetPath: env.FRIGATE_RTSP_PASSWORD_HOUSE_SIDE
      optional: false
    - kind: Secret
      name: frigate
      valuesKey: rtsp_password_front_yard
      targetPath: env.FRIGATE_RTSP_PASSWORD_FRONT_YARD
      optional: false
