---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app frigate
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: frigate
      version: 8.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: emqx
      namespace: home
  # - name: intel-gpu-plugin
  #   namespace: kube-system
  # - name: node-feature-discovery
  #   namespace: kube-system
  values:
    global:
      nameOverride: *app
    image:
      repository: docker.io/blakeblackshear/frigate
      tag: 0.11.0-beta4
    env:
      TZ: America/New_York
      FRIGATE_MQTT_PASSWORD: ${SECRET_MQTT_PASSWORD}
      PLUS_API_KEY: "${SECRET_FRIGATE_PLUS_API_KEY}"
      # LIBVA_DRIVER_NAME: "i965"
      # FRIGATE_MQTT_PASSWORD: "Afaqn2oBGbQJwIJzz8CvuYYsx2NtZ5"
    service:
      main:
        ports:
          http:
            port: &port 5000
          rtmp:
            enabled: true
            port: 1935
            protocol: TCP
            targetPort: 1935
    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /api/version
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness:
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /api/version
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      startup:
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /api/version
            port: *port
          failureThreshold: 30
          periodSeconds: 10
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cctv"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
          - host: "frigate.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "frigate.${SECRET_DOMAIN}"
            secretName: "frigate-tls"
    securityContext:
      privileged: true
    configmap:
      config:
        enabled: false
    podAnnotations:
      configmap.reloader.stakater.com/reload: frigate
    nodeSelector:
      kubernetes.io/hostname: "inky"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - inky
    persistence:
      config:
        enabled: true
        type: configMap
        name: frigate
        subPath: config.yaml
        mountPath: /config/config.yml
        readOnly: true
      data:
        enabled: true
        existingClaim: frigate-data-pvc
      media:
        enabled: true
        # type: nfs
        # server: "${TRUENAS_SERVER}"
        # path: /mnt/tank/data/frigate
        # mountPath: /media
        existingClaim: frigate-media-pvc
      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 2Gi
        mountPath: /dev/shm
