---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - data-pv.yaml
  - media-pv.yaml
  - helm-release.yaml
  - secret.sops.yaml
configMapGenerator:
  - name: frigate
    files:
      - config.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
