---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media-v1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 700Gi
