# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: frigate-secrets
    namespace: home
type: Opaque
stringData:
    mqtt_user: ENC[AES256_GCM,data:PAkubYp6YLLga8sO,iv:odJ0wXVQTH4P09LofimWVPh8/Nq1foPRktxu0hNeyWQ=,tag:szZlmHG2Xor9DCcXwoSyTg==,type:str]
    mqtt_password: ENC[AES256_GCM,data:Q0FPSdpimMxFnOxVdtVM/NeZWLyqxDX3hNVmfVCy,iv:IlfycjPynvoon4MV2HnybTp71pgN5YxFVimtqOP885Y=,tag:+mDPoFncim1h//gvIONzcw==,type:str]
    plus_api_key: ENC[AES256_GCM,data:kw08oJAY6QoE/41o6dnBxwpLMTigj3sSUG5ppIUQmi0zsovkycIufKUnP973NhrqOCkTr2m7kuTVt05EC6ssXuNB1CftCCLANGAN66A=,iv:Y3rYk8am7dNHbxtygVbMLGz1MTZSSotDA4EFz6B0U+0=,tag:0Fy73FK9V2yLHgPvUZXNuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p3uljw85dn69pj2q0j4sane83hhzlpywrmrs3pwkgfs6g299rg3su5udnm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZk42SUpxbUpJVkVrZ040
            SDVycFMxVGFpUXNMbm5NcDA4cTNNaWZlSDBRCmJPN09DckN5bktyL2hvdTdnWVBL
            bmhZK1ZSdVpVTVRMSlRhQVRxSitJOU0KLS0tIFFHTGxIcGNaUEFPNm9hT3ZaaWZ5
            dElRWENRMDhJL2pJRlpaeGxud0JocU0KNCCGUAG1Eu3LHWUTrPAHcHYDITr0BrMc
            FrM17A1DttOUCCU8nOLYCloeZ0LYohZp12eAb1P2gy5BFXSUhsLGjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-04T20:56:17Z"
    mac: ENC[AES256_GCM,data:cvJ+gYRuJOn3M0/ABEZNS9IFL8VsubZHpzUg9QH8DWxPOPorGYZqOAKfixjDQSaj8vTTAqEt/R6/doqmFvtKfM+FadCMquSpY/9PYC4Zu9B0e0lmP0+gNrxfUS5NkNAXYHZ3EEUffeDhYtKgT/j1ZbWiIvV+1uP98qHZDZUgVvg=,iv:Op4cR/xL2fMMjeEOowa+fUGCcHYur/RkHpAhIShAsEw=,tag:YrbveAolzX+LMPdC3KBENw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
