---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rxresume
  namespace: collab

spec:
  interval: 5m

  chart:
    spec:
      chart: ./charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m

  install:
    timeout: 10m
    remediation:
      retries: 3

  upgrade:
    timeout: 10m
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true

  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true

  values:
    imagePullSecrets:
      - name: "regcred"

    image:
      repository: amruthpillai/reactive-resume
      tag: v1

    nameOverride: rxresume

    # env:
    #   FIREBASE_APIKEY: ${SECRET_RXRESUME_FIREBASE_APIKEY}
    #   FIREBASE_APPID: ${SECRET_RXRESUME_FIREBASE_APP_ID}
    #   FIREBASE_AUTHDOMAIN: ${SECRET_RXRESUME_FIREBASE_AUTHDOMAIN}
    #   FIREBASE_DATABASEURL: ${SECRET_RXRESUME_FIREBASE_DATABASE_URL}
    #   FIREBASE_MESSAGINGSENDERID: ${SECRET_RXRESUME_FIREBASE_MESSAGING_SENDER_ID}
    #   FIREBASE_PROJECTID: ${SECRET_RXRESUME_FIREBASE_PROJECT_ID}
    #   FIREBASE_STORAGEBUCKET: ${SECRET_RXRESUME_FIREBASE_STORAGE_BUCKET}

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true

        ingressClassName: "traefik"

        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "file-account"

          cert-manager.io/cluster-issuer: letsencrypt-staging
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"

        hosts:
          - host: &host cv.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix

        tls:
          - hosts:
              - *host

            # resources:
            #   requests:
            #     memory: 100Mi
            #     cpu: 100m
            #   limits:
            #     memory: 500Mi
