---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-data-pv
  namespace: monitoring
spec:
  storageClassName: alertmanager-data-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/volume2/Docker_Vol/alertmanager_data"
  mountOptions:
    - nfsvers=4.1
    - hard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-data-pvc
  namespace: monitoring
spec:
  storageClassName: alertmanager-data-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
