---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alert-manager-pv
  namespace: monitoring
  labels:
    app.kubernetes.io/name: "alert-manager"
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.1
    - hard
  nfs:
    path: /volume2/DockerVol/alertmanager_data
    server: ${NAS_ADDR}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alert-manager-pvc
  namespace: monitoring
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
