---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data-pv
  namespace: monitoring
spec:
  storageClassName: prometheus-data-nfs
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/volume2/Docker_Vol/prometheus_data"
  mountOptions:
    - nfsvers=4.1
    - hard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-pvc
  namespace: monitoring
spec:
  storageClassName: prometheus-data-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
