---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: anonaddy-redis-data-pv
  namespace: privacy
spec:
  storageClassName: anonaddy-redis-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/volume2/DockerVol/anonaddy_redis_data"
  mountOptions:
    - nfsvers=4.1
    - hard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anonaddy-redis-data
  namespace: privacy
spec:
  storageClassName: anonaddy-redis-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
