---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app anonaddy
  namespace: privacy

spec:
  interval: 5m

  chart:
    spec:
      chart: anonaddy
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m

  values:
    global:
      nameOverride: *app

    image:
      repository: anonaddy/anonaddy
      tag: 0.12.3

    env:
      TZ: ${TIMEZONE}
      # -- Application key for encrypter service
      # You can generate one through `anonaddy key:generate --show` or `echo "base64:$(openssl rand -base64 32)"`
      # APP_KEY: USING SECRET
      # -- Root domain to receive email from
      ANONADDY_DOMAIN: ${SECRET_DOMAIN}

    envFrom:
      - secretRef:
          name: *app

    ingress:
      main:
        enabled: true

        ingressClassName: "traefik"

        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "cctv"
          hajimari.io/group: privacy

          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"

        hosts:
          - host: &host "anonaddy.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix

        tls:
          - hosts:
              - *host

    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      config:
        enabled: true
        existingCLaim: anonaddy-config-pvc

    # https://github.com/bitnami/charts/tree/master/bitnami/mariadb/#installing-the-chart
    mariadb:
      enabled: true

      primary:
        podSecurityContext:
          enabled: true
          fsGroup: 65537

        containerSecurityContext:
          enabled: true
          runAsUser: 1031

        persistence:
          enabled: true
          existingClaim: anonaddy-mariadb-data-pvc

      auth:
        database: *app
        username: *app

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true

    # -- Enable and configure redis subchart under this key.
    #    For more options see [redis chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/redis)
    # @default -- See values.yaml
    redis:
      enabled: true

      architecture: standalone

      global:
        storageClass: "nfs-client"

      securityContext:
        sysctls:
          - name: net.core.somaxconn
            value: "10000"

      master:
        podSecurityContext:
          fsGroup: 65537
          supplementalGroups:
            - 65537

        nodeSelector:
          beta.kubernetes.io/arch: amd64

        persistence:
          enabled: true
          existingClaim: anonaddy-redis-data

      auth:
        enabled: true
        existingSecret: *app
        existingSecretPasswordKey: REDIS_PASSWORD

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true

  valuesFrom:
    - kind: Secret
      name: *app
      valuesKey: ANONADDY_SECRET
      targetPath: env.ANONADDY_SECRET
      optional: false
    - kind: Secret
      name: *app
      valuesKey: APP_KEY
      targetPath: env.APP_KEY
      optional: false
    - kind: Secret
      name: *app
      valuesKey: MARIADB_PASSWORD
      targetPath: mariadb.auth.password
      optional: false
