---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: privacy
resources:
  - anonaddy-mariadb-pvc.yaml
  - anonaddy-redis-pvc.yaml
  - config-pvc.yaml
  # - mariadb-helm-release.yaml
  # - redis-helm-release.yaml
  - helm-release.yaml
  - secret.sops.yaml
