---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: anonaddy-redis
  namespace: privacy
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 17.0.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  values:
    architecture: standalone
    securityContext:
      sysctls:
        - name: net.core.somaxconn
          value: "10000"
    global:
      storageClass: "nfs-client"
    master:
      podSecurityContext:
        fsGroup: 100
        supplementalGroups:
          - 100
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      persistence:
        enabled: true
        existingClaim: anonaddy-redis-data
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    auth:
      existingSecret: anonaddy
      existingSecretPasswordKey: REDIS_PASSWORD
