---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapdrop
  namespace: tools
spec:
  interval: 10m0s
  chart:
    spec:
      chart: snapdrop
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: linuxserver/snapdrop
      tag: version-724f0af5
    env:
      - TZ: ${TIMEZONE}
      - PGID: 1031
      - PUID: 65537

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 60
            preference:
              matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - arm64
