---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-config-pv
  namespace: media
spec:
  storageClassName: transmission-config-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/volume2/DockerVol/transmission_data"
  mountOptions:
    - nfsvers=4.1
    - hard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config-pvc
  namespace: media
spec:
  storageClassName: transmission-config-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
