---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-downloads-pv
  namespace: media
spec:
  storageClassName: transmission-downloads-nfs
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/volume2/Downloads"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-downloads-pvc
  namespace: media
spec:
  storageClassName: transmission-downloads-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
