---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-media-pv
  namespace: media
spec:
  storageClassName: transmission-media-nfs
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/volume2/Media"
  mountOptions:
    - nfsvers=4.1
    - hard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-media-pvc
  namespace: media
spec:
  storageClassName: transmission-media-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
