apiVersion: v1
kind: Secret
metadata:
    name: transmission
    namespace: media
stringData:
    #ENC[AES256_GCM,data:aJ0sB0hZp+qZmBkndcdjaDXe,iv:rorFzDlhBCgOL1uI8s4xlEl9jhEO4fi3FODonLN5pO4=,tag:CUbvNvbFxRPTRGUdfxxjgw==,type:comment]
    TRANSMISSION_RPC_USERNAME: ENC[AES256_GCM,data:Zz+0wDS07TysHqTS7o1J,iv:LqVqU/bTtbdvLnZ8cttiV9/oo0cjt9YjAF9Bs78x9n0=,tag:aGfXcrAO/tn1do/+lp8aXQ==,type:str]
    TRANSMISSION_RPC_PASSWORD: ENC[AES256_GCM,data:dosDtAQokTGg34O9bnoU8qBd/WLaA3JiL0Hz9KD4KOP+Hv57VWSNilfbb2J4JF5eZ5YhaosQ/adozHI1O31Jog==,iv:ViJz0oXb/ZWrubniGInOw4Yw4rEZHBG8q74ZL+yHa3I=,tag:anyQ803g25WyCvAEo3HwLw==,type:str]
    TRANSMISSION_PEER_PORT: ENC[AES256_GCM,data:7Hf754Y=,iv:Ot2Pspn2s9pAVPFUOW1wCDq1KQvBZw0MPLixDLgYciU=,tag:dZEjl+zEuutD+5vKApnU5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p3uljw85dn69pj2q0j4sane83hhzlpywrmrs3pwkgfs6g299rg3su5udnm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UWlaK0dNTm5nbkdsa3hx
            T2hJYnVZLzRDSDl3d0pqOGRtcGZ5T3pqMjFzCk9sOWQrd2JEb2w2dzFyQm5tRyt0
            UWtaaUUyZ0ptSEE2U0cwamxoOWlIdHMKLS0tIEhFQ0dzUS9JOGlKelR1NXVTL1hw
            emNobzhvV1ZpNEM5ZjN2ZW91cGRmWlUK2odNPQhqxWIQ7FpNHi4DfTFajYgWnOoQ
            tB0xIRsNNxfVRjtzH5JGCSmVYRepLzGU77p3fYbSQB42y7WTOsKDXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-08T03:45:10Z"
    mac: ENC[AES256_GCM,data:hauUAc8E6O+icD8g9FBXIvShmL47zTtJbzIpCnhEHM1oCOPQbYSeTTVM2T3OHE163F6L1XF6FAuWLAiI1jh5DGco/b5yDf3qszKvFlJnSoiJcqBN+E+BT5HPZ8+7rfGrP1NVKU7K3KrqhdR5eB0KTF+d1EDmkPBN34hEnm9zVtY=,iv:VBSTSkxOVsV0wzrnPRspA7Hu3quuTZYhkZZAAaQjyOw=,tag:x0ME1dnJFwLF9a5q5V4QmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
