apiVersion: v1
kind: Secret
metadata:
    name: transmission-secret
    namespace: media
stringData:
    CONFIG_FILE: null
    TRANSMISSION_RPC_USERNAME: ENC[AES256_GCM,data:4YiJ8giHxG6KKkgEHZAm,iv:OuZBZTdg71Flefd7u7Ojjx1igp2CukS7t5UeTbHcnZc=,tag:cIs13vmJLiZlaFRNYAjTTg==,type:str]
    TRANSMISSION_RPC_PASSWORD: ENC[AES256_GCM,data:oXVu2EWOZnwIx3n8e6BX9gJPJZ1xZPD/lw/Tu/RiClpRw1cIYDd1LJffVwW43Zwhy6kwsBK6GY8zupexxPOogw==,iv:I+L0hXvbxvAZ4YhF3DXLxqthw2W6iAUuYM+Ir9lVP0g=,tag:ah+PVvhnNUAZb+fU8lIBWQ==,type:str]
    TRANSMISSION_PEER_PORT: ENC[AES256_GCM,data:YCf6xYg=,iv:lVtyY170U9IIoNvid2b8cvL5IGjRhXpfWWYP91iicdg=,tag:ciBFDd0rsYktVuXBfrsn6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p3uljw85dn69pj2q0j4sane83hhzlpywrmrs3pwkgfs6g299rg3su5udnm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ekpYYjBXa2gvRElZckp1
            NmI5ZmdWT2tQdHF0eDFmZjV3UmlsMlZDTzNRCkRqTVMxbVc4b1NmcW91Zk14K2g2
            Z092MlVFY29oRW5WaW9TODd4OUIwYWcKLS0tIG92UjNQTVpvcHNLRTBBL25aelVQ
            RC9pMDdsaW5oVVhKaURJQnRZMFdCYTAKHxIuOyVJsutVWyJwRKVpsQw90Fv+yB4g
            E6W9+v+7F/A/ZbYL6LouR7geT3u52qKPF8hX4TxFgRupYi6JzSLP5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-07T22:31:33Z"
    mac: ENC[AES256_GCM,data:qtKuPAvV37TUKKl4vxylDSs+TnA4gEI1p99iiYYzEVKugPN6gCkpMo4IjbNr69km2sUZ/xkGbKMHsB8zIKlcjUOyVlkNFVjDHu+KnrxTfU+31eCHavaAi//3VGEW8Mc6ufqM0GcIkdfOv2E6hNtB3OZ1x96EAOeQ7x0dDfIXMP0=,iv:rAaSGW7BbsRugcgHHPBPshIieeiAjV2aNCIxhPU/TGU=,tag:FQCVfLfWbOJ9QBJ1y6Musw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
