---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - bookstack
  # - gollum
  # - joplin
  # - recipes
  # - rxresume
  # - teamspeak
  # - vikunja
  # - yourls
