---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - tls-store
  - dashboard
  - middlewares
  - routers
  # - external-services
  - service-monitor.yaml
