---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth
  # - biz-ops
  # - db
  - default
  - flux-system
  - home
  - kube-system
  - media
  - monitoring
  - networking
  # - security
  # - system-upgrade
