# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd
    namespace: media
type: Opaque
stringData:
    SABNZBD__API_KEY: ENC[AES256_GCM,data:Fb+Zw9CrvUXfsWelv1vWS0xt0RQOmgGRFDUpcCgiPAw=,iv:50MU4Ec65Qq0+q0sPQu8oXv+n89pdnfhYNeHhytIOVo=,tag:XB2WXORkKMEF3jwg674Lnw==,type:str]
    SABNZBD__NZB_KEY: ENC[AES256_GCM,data:pjce22UkwOryeaPDsqzsSRdciZuYp/Rz+pbGiBbfBsg=,iv:1ZUll8gpimH+77JWp67DHbPscNpt5Qtv3knRjosHWhk=,tag:L9S0ekjYI32z8vk5vVnTvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzrw396e67z9wdzsxzdk7ka0g2gr3l460e0slaea563zll3hdfqwqxdta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTHF2WnpGUlJZMHZzaHpt
            eDRlaFpsV2FvM0NsWDhpbXZUT2xscGZLU1JNCldCaFRkQXpOUUlFYXFQeFZNZDJW
            WVI0TElGdWgvSVY2eVE4MFZJMTA4S00KLS0tIEJxbWc3Vi9GSnpYeWdKS1ZGdSt4
            WGxvOWp6WCtESjhRTjUxQzhXdEFoR00Kwzdyu/jzqKVkw0CFfFJZys6ZMwmTo13r
            57DoIO2tka/67G+0p+LJfzHss5BcPfoYjHLte6PDUTU7KySnAWfALQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-02T18:59:07Z"
    mac: ENC[AES256_GCM,data:xfZ2KTFSY/go9uNIHC3BE3HjleLu9eNor6QLLc7rOBI70Tybx6dIJJrX948TP0nwFxXfMRo1lghZUi1FURMOfGoYABadcOwuz0objJu2d9JIusC8O6/6ITl7n1akGbbUenIL5T6mTT2YIJHnYZBgFvfhuz/vXq9zVQ315wnQF8g=,iv:pKkrxIA3uqSjd+btSsAEUEvTDocbkWL32wRCcBMbd28=,tag:TUHjIbSB2wCFXRD8th/ycg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
