---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: emqx-wss
  namespace: home
spec:
  entryPoints:
    - wss
  routes:
    - match: HostSNI(`emqx-ws.${SECRET_DOMAIN}`)
      services:
        - name: emqx
          port: 8083
      middlewares:
        - name: networking-internal-only@kubernetescrd
  tls:
    secretName: ${SECRET_DOMAIN/./-}-tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: emqx-mqtt
  namespace: home
spec:
  entryPoints:
    - mqtts
  routes:
    - match: HostSNI(`mqtt.${SECRET_DOMAIN}`)
      services:
        - name: emqx
          port: 1883
      middlewares:
        - name: networking-internal-only@kubernetescrd
=  tls:
  secretName: ${SECRET_DOMAIN/./-}-tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: emqx-dashboard
  namespace: home
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`emqx.${SECRET_DOMAIN}`)
      kind: Rule
      services:
        - name: emqx
          kind: Service
          port: 18083
      middlewares:
        - name: networking-bloopnet-xyz-auth@kubernetescrd
  tls:
    secretName: ${SECRET_DOMAIN/./-}-tls
