---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: chain-internal-wutanglan-auth
  namespace: networking
spec:
  chain:
    middlewares:
      # Note this requires cloudflare proxy
      - name: networking-internal-only@kubernetescrd
      - name: networking-secure-headers@kubernetescrd
      - name: networking-rate-limit@kubernetescrd
      - name: networking-authelia@kubernetescrd
      - name: networking-error-pages@kubernetescrd
