apiVersion: v1
kind: Secret
metadata:
    name: security
    namespace: networking
stringData:
    JWT_TOKEN: ENC[AES256_GCM,data:bliHEwOumASVI1Mab6LVso0W0LTdMNNFJdTonLxViv3KcUXkXKLyfl1mTUyX3p8V5a4gNYw/wy8EPJRqv9h9xw==,iv:lOigpUDMnatEAVxdIsK+WB26k4fhTGFGTiTGBkbVaS0=,tag:7FyB3K0kDAq5rcuG4VOUGw==,type:str]
    SESSION_ENCRYPTION_KEY: ENC[AES256_GCM,data:zJWIXDjver04odTl0IMa5LePr9KLDgc4AXKnEbicerfp4FqF+zsdyWHRuWOx6vjwdpLZ/bge5mzPSQzAA1YbkkbZElkvnyh2twrJuhY=,iv:E2wIiK4WVsuZ4JUjNYqxfTNXxlbKK7usGxevk6JsjEk=,tag:Pm+M824cSgaopmCoO1K/ww==,type:str]
    STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:xtex39a1YOIrhXRizXVhNv1eIpDcNKXfg7OBP/+32LJzzXI+I2NtGGDkruOHTt9xP7e6zRUWxo4eH/Coztbm40UcyWV/,iv:X0NkJcTUz/y0+YoT9dDRV+VHv/JCKu5H3K3tGBWw9wc=,tag:H4PSp80RZuw3KXqYIZjrVQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:CdzuHuAvpRgLJl3znj1wKDLC8ghrbmLqONtk0qqczk3KV/efp0XYuX4lgFhEpC/a+pJvQHvYTOo0mHsPm6ChWA==,iv:MCoTe5m7deb9LYfJZsD5oPe53vC0PfhNLQT2vS7oJuI=,tag:d+nqSmp4ULxOKMXwPglj+g==,type:str]
    STORAGE_PASSWORD: ENC[AES256_GCM,data:vHM7ncPNKAPHxWkQZwc/AF7ixWsF6sj7D0GaZfyNvL9ln67x/DyHIxxhgvlMFQzHCyohSfMOLxnBQSUCo0e/mQ==,iv:4ITO3OZyy9voXx+MEEqM3pUXl07JjRdPWE6zDEwJUTE=,tag:Ey1+yfd+Fv37skAcorncAw==,type:str]
    #ENC[AES256_GCM,data:oGyZ8XDt/n5AigvV+Ffm,iv:bmQ+Ck8BbvUZKQLlC4SL7L+ewuX3/gq4VY9m/VVU950=,tag:yiLzXFG2xYaXamuH+1dgKQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p3uljw85dn69pj2q0j4sane83hhzlpywrmrs3pwkgfs6g299rg3su5udnm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNazByTWc3YzNJbFYwMkMv
            SDJSa2VpbDdDcFhkdW5JQWxscDVSYjlwZ2pZCk81RXFkYXdaWnFCZk1paEIxSmlw
            ZEd2ZTd1MTl2NGNGdTUxWUhldEs3SWsKLS0tIDBjSWphTWhtaDdOVVdKZ1RiL2xh
            REs3dUZFdHNrUWE5aFhvdGxLT0t0YTQK2761OShR/bUK/0XN0TBea547uxXnmKWf
            NupvIIKRDgEXHom+P+w47H2FCMiFs+Ze1ZWt4+Q0e6UEzO0ZgfDHBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-08T20:35:03Z"
    mac: ENC[AES256_GCM,data:TR/yyZ1wnbWTuwyprO4q9xT+cSo+K52oiqCgPaVMf4CnnU/2QvNBcVq9uiS3mFoKO/Cv7EIbDA3kZy8JcuRc7vNYRUpevMztYDkGrbNn4SHTXQ/PYb301tv+b5yjfV9s8JNl+NkDlMm8fQBc6x5YqGedr0l+P4ApwU6oK2yvph0=,iv:b0ALWs+EYuhzapejoDJArVxPmEBH/hjqMJZQZ522J6M=,tag:hG9CAr0tgEmKc2feiYCYRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
