---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authelia-data-pv
  namespace: media
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    # - rsize=1048576
    # - wsize=1048576
  nfs:
    path: /volume2/DockerVol/authelia_data
    server: ${NAS_ADDR}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-data-pvc
  namespace: media
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
