apiVersion: v1
kind: Secret
metadata:
    name: authelia
    namespace: security
stringData:
    JWT_TOKEN: ""
    STORAGE_PASSWORD: ""
    SESSION_ENCRYPTION_KEY: ""
    STORAGE_ENCRYPTION_KEY: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p3uljw85dn69pj2q0j4sane83hhzlpywrmrs3pwkgfs6g299rg3su5udnm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dTNsSlVsTTRZSmFyQmRJ
            eGV0WWx0dmR2VFBxdkY1TnVNWldIdnowZUg0ClJDKzZCLzlQU0EyQnJydzlMbEM1
            Um1rZlVKVnZ1MEZhejRlMTdQbjZpeTQKLS0tIGhsZ2VyUUZkbzhST1RLdTQzVjB2
            YkRJVUdUTFUzV1NldGpubjQvZGtlNDQKIO6WFQ0FzHgQ66xP5vvoF7GtttPSAmei
            B9KWXFhW2JrCbgxXX/smMxemrSnF0xpTvw4z92aEysUMuUCc01eEMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-08T07:54:53Z"
    mac: ENC[AES256_GCM,data:F+jwu2SXpnhWNZo7MVC0Ty37KI5jKJtY3LoE55cUxiYjnYnAyXhTeO6dqEUGeamo5cx/ZcBr1D9fLv6Rl6IzDv5L//1IEIVx8I3qAO588L61a10Fmc1trkco+lr61/veNAA+EaaeKPtAupR4tkPs7thNTCpctXACpIPonL3cRH4=,iv:lyUKFdzmSibIRGZEL7K7iBgDyy4hfxyJr/pJ/d1Rfis=,tag:Mf8VvXqM1zZbyLPwzC29nw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
