---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stash-config-pv
  namespace: media
spec:
  storageClassName: stash-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/volume2/DockerVol/stash_config_data"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-config-pvc
  namespace: media
spec:
  storageClassName: stash-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
