---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app stash
  namespace: media
spec:
  releaseName: stash
  interval: 15m
  chart:
    spec:
      chart: stash
      version: "3.3.2"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
    interval: 15m
  timeout: 5m
  values:
    image:
      tag: v0.16.0 # {"$imagepolicy": "flux-system:stash:tag"}
    controller:
      replicas: 1 # active longhorn-webapp nas
    env:
      TZ: America/New_York
    persistence:
      config:
        enabled: true
        existingClaim: stash-config-pvc
      media:
        enabled: true
        existingClaim: stash-media-pvc
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cctv"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
          - host: &host "stash.${SECRET_DOMAIN}"
            paths:
              - path: "/"
        tls:
          - hosts:
              - *host
            secretName: *host
    nodeSelector:
      kubernetes.io/hostname: "clyde"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - clyde
