---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-config-pv-v1
  namespace: db
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    # - rsize=1048576
    # - wsize=1048576
  nfs:
    path: /volume2/DockerVol/postgres_data
    server: ${NAS_ADDR}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-config-pvc-v1
  namespace: db
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
