---
- name: coredns - create coredns data directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ unifi_onboot_directory }}/coredns"

- name: coredns - create coredns boot script
  ansible.builtin.template:
    src:
