---
- name: "haproxy - pull latest version"
  raw: "podman pull haproxy:latest"

- name: "haproxy - stop haproxy"
  raw: "podman stop haproxy"

- name: "haproxy - remove haproxy"
  raw: "podman rm haproxy"

- name: "haproxy - create new haproxy container"
  raw: "/bin/bash {{ unifi_onboot_directory }}/10-onboot-haproxy.sh"
