---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  # - jellyfin
  # - lidarr
  # - media-browser
  # - overseerr
  # - plex
  # - prowlarr
  - qbittorrent
  # - radarr
  # - radarr-uhd
  # - readarr
  # - recyclarr
  # - sabnzbd
  # - scripts
  # - sonarr
  # - sonarr-uhd
  # - tautulli
  # - unpackerr
  - stash
  - transmission
