---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shlink-config-pv
  namespace: tools
spec:
  storageClassName: shlink-config-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/volume2/DockerVol/shlink_data"
  mountOptions:
    - nfsvers=4.1
    - hard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shlink-config-pvc
  namespace: tools
spec:
  storageClassName: shlink-config-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
