---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app shlink
  namespace: tools
spec:
  interval: 5m
  chart:
    spec:
      chart: frigate
      version: 8.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m

  install:
    createNamespace: true
    remediation:
      retries: 5

  upgrade:
    remediation:
      retries: 5

  dependsOn:
    - name: redis
      namespace: dbms

  values:
    global:
      nameOverride: *app
    image:
      repository: shlinkio/shlink
      tag: 3.1.2

    env:
      - TZ: ${TIMEZONE}
      - DEFAULT_DOMAIN: go.${SECRET_DOMAIN}
      - USE_HTTPS: "true"
      - VALIDATE_URLS: "true"
      - INVALID_SHORT_URL_REDIRECT_TO: https://${SECRET_DOMAIN}
      - REGULAR_404_REDIRECT_TO: https://${SECRET_DOMAIN}
      - BASE_URL_REDIRECT_TO: https://${SECRET_DOMAIN}
      - REDIS_SERVERS: redis://redis.dbms.svc.cluster.local:6379
      - REDIRECT_APPEND_EXTRA_PATH: "true"
      - AUTO_RESOLVE_TITLES: "true"
      - ENABLE_PERIODIC_VISIT_LOCATE: "false"

    ingress:
      main:
        enabled: true

        ingressClassName: "traefik"

        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "link"
          hajimari.io/group: tools

          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"

        hosts:
          - host: &host "go.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix

        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: shlink-config-pvc
        mountPath: /etc/shlink/data/database.sqlite
        subPath: database.sqlite
