---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: matrix-synapse-admin
  namespace: comms
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  dependsOn:
    - name: matrix-synapse
      namespace: comms
  values:
    image:
      repository: awesometechnologies/synapse-admin
      tag: latest
    nameOverride: matrix-synapse-admin
    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true

        ingressClassName: "traefik"

        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "format-list-checks"

          cert-manager.io/cluster-issuer: letsencrypt-staging
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-chain-no-auth@kubernetescrd"

        hosts:
          - host: &host matrix-admin.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix

        tls:
          - hosts:
              - *host

    postgresql:
      enabled: false

    probes:
      liveness:
        enabled: false
        # custom: true
        # spec:
        #   failureThreshold: 5
        #   httpGet:
        #     path: /_matrix/mau/live
        #     port: http
        #     scheme: HTTP
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 1
      startup:
        enabled: false
        # custom: true
        # spec:
        #   failureThreshold: 5
        #   httpGet:
        #     path: /_matrix/mau/live
        #     port: http
        #     scheme: HTTP
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 1
      readiness:
        enabled: false
        # custom: true
        # spec:
        #   failureThreshold: 5
        #   httpGet:
        #     path: /_matrix/mau/live
        #     port: http
        #     scheme: HTTP
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 1
