---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mailu-storage-pv
  namespace: biz-ops
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.1
    - hard
  nfs:
    path: /volume2/DockerVol/mailu_data
    server: ${NAS_ADDR}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailu-storage
  namespace: biz-ops
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
