---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailu-storage
  namespace: biz-ops
spec:
  storageClassName: longhorn-backup
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
