---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailu-postgresql
  namespace: biz-ops
spec:
  storageClassName: longhorn-backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
