---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mailu-postgresql-data-pv
  namespace: biz-ops
  labels:
    app.kubernetes.io/name: "mailu-postgresql"
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.1
    - hard
  nfs:
    path: /volume2/DockerVol/mailu_postgres_data
    server: ${NAS_ADDR}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailu-postgresql-data-pvc
  namespace: biz-ops
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
