# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: plex-jbops
    namespace: media
type: Opaque
stringData:
    config.ini: ENC[AES256_GCM,data:BjfNljnQfdkNjZKnnFxperbNrbpz9jzoaG85tyiqjv1Vej1Krr4M7+1ZrkgXKgoDzjYeutiqFDST+fpvXvNfemUrLwqpmAVN8GrfD34=,iv:XA2JQChYTOGssVV+xOnBfXtQYyuOND+Ib8KqK1cNbRg=,tag:w/pDi5iy+BoGBeLp4+YGTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15uzrw396e67z9wdzsxzdk7ka0g2gr3l460e0slaea563zll3hdfqwqxdta
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SzdoQ0loZ3lXSVhTa2xx
            SWRGZGEwR2NQQjFLSlpXOGs4dHRpMFpYdURRCjFEY1dtTVY1RXhuRWx2N1ZFV25l
            SHhsZlozMWV4ck0vR1o0Sncwd2NXRlEKLS0tIDZLcWswWEp6dGtycFVONy9xNnl0
            aUV2RmN2U2MyZEUrbUZnVlY3d3hIcFUKp40tmI5HM3iumet9Z04aU/MdBDEWbWhi
            zlOcZFKkgrL5a1HyBkv4eXWIas10C2cci0cd3Q6Z2UCFgEHWuki5JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-04T13:41:06Z"
    mac: ENC[AES256_GCM,data:usClxokIRAXngGEZkrJuYN5N1boyAq3tMWcesgaXzbY3NApM5UtHNrNgd+FdI6am9X5RicnCSHTG1BEFh5Lu0uDItDr2BUgw8JhZFXbiOIxfoK8s8c7VJG/Cd53uxuVgAwtnaG7mYPl7yOhEUHxVCS3Z5Fjn9NjpU/pInVzZEw8=,iv:CzsEuYMpGO4K2eojetbLxEbdefXlmZ0hFzrCpxcl6iQ=,tag:lcJIV6xoL1DOZop1nMTnhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
