---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstack-config-pv
  namespace: collab
spec:
  storageClassName: bookstack-config-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/volume2/DockerVol/bookstack_data"
  mountOptions:
    - nfsvers=4.1
    - hard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-config-pvc
  namespace: collab
spec:
  storageClassName: bookstack-config-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
