---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstack-mariadb-data-pv
  namespace: collab
spec:
  storageClassName: bookstack-mariadb-data-nfs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_ADDR}
    path: "/volume2/DockerVol/bookstack_mariadb_data"
  mountOptions:
    - nfsvers=4.1
    - hard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-mariadb-data-pvc
  namespace: collab
spec:
  storageClassName: bookstack-mariadb-data-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
