apiVersion: v1
kind: Secret
metadata:
    name: bookstack
    namespace: default
stringData:
    MARIADB_PASSWORD: ENC[AES256_GCM,data:6lYxEwQ+k8Omh4Wam5ZFOJvSb3Gisn41fRmiq3LAQvJjKFLGnz12LZ8rhQnk3DjSptArzqpCXWvkEu/QEulOzA==,iv:p92fAjBciAfFNApz4TF5jV+21n8Bi2yLR7Dw5hKGoRg=,tag:TpRv+k+izmL2/YBgTHvtLg==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:g1fPnpcOiZ0QbuUOhdqbqM/IWlkzwOc0sqgq9avzNpvpWo5EyoN0nr9bQpsp+QZB8q9T62UwtS7xaCfpA5p7Qw==,iv:ZHQ52wQsmgLy3Lo5o33hmn4d37p9qaRfDno7lSxBC6E=,tag:X6htEcfXLEyMXMWbiHHkdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p3uljw85dn69pj2q0j4sane83hhzlpywrmrs3pwkgfs6g299rg3su5udnm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaElrdVBzcm9Fck9lSFcw
            a01jOC9WcVBPWjFBWUxHTU90amdvaWtrbDI0CllXZG1aeDhwbFlTOGJYaDNFWU8z
            M2wwR0lWRXhBYkt2QXJnbVNjc3A1YTgKLS0tIHFPK0ljalJwV2hWUWtCUnJCbnk0
            NnR1WmpPMFo5bGRsNUNLQUtaOTZHNU0K4A9k2/y/WgOWD+YcBxoIG3gl+Ke+K437
            zpEDTD1AkBKiPqCywbVAFQ/nObrqN/4n8xYQ+DA3RtIBU5G0oD2akQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-26T14:18:42Z"
    mac: ENC[AES256_GCM,data:tpE4bSDotqZV2t18NADOXR3qPIVYjRl0kDgeADlahAAj68Vex9T2AE4h31piQ314W48yUb85plV497uPA3CfVXtonQ5GvWgZtqiSD3bH7VpnSDp39k28kV6cScpshO7tgzZQrI2XbRD7l0cbWzo1i/rWFB3LakVx+6zAbkt9KdY=,iv:+xP5upRt69Tg/QkRNZ5p1Wh2gWHtW75QckXzwCcaLak=,tag:2A/mjp4vhcVBq31YBtczYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
